// CODE GENERATED BY github.com/volvo-cars/lingon. DO NOT EDIT.

package computenetworkfirewallpolicyrule

import (
	hclwrite "github.com/hashicorp/hcl/v2/hclwrite"
	terra "github.com/volvo-cars/lingon/pkg/terra"
)

type Match struct {
	// DestIpRanges: list of string, optional
	DestIpRanges terra.ListValue[terra.StringValue] `hcl:"dest_ip_ranges,attr"`
	// SrcIpRanges: list of string, optional
	SrcIpRanges terra.ListValue[terra.StringValue] `hcl:"src_ip_ranges,attr"`
	// Layer4Configs: min=1
	Layer4Configs []Layer4Configs `hcl:"layer4_configs,block" validate:"min=1"`
	// SrcSecureTags: min=0
	SrcSecureTags []SrcSecureTags `hcl:"src_secure_tags,block" validate:"min=0"`
}

type Layer4Configs struct {
	// IpProtocol: string, required
	IpProtocol terra.StringValue `hcl:"ip_protocol,attr" validate:"required"`
	// Ports: list of string, optional
	Ports terra.ListValue[terra.StringValue] `hcl:"ports,attr"`
}

type SrcSecureTags struct {
	// Name: string, required
	Name terra.StringValue `hcl:"name,attr" validate:"required"`
}

type TargetSecureTags struct {
	// Name: string, required
	Name terra.StringValue `hcl:"name,attr" validate:"required"`
}

type Timeouts struct {
	// Create: string, optional
	Create terra.StringValue `hcl:"create,attr"`
	// Delete: string, optional
	Delete terra.StringValue `hcl:"delete,attr"`
	// Update: string, optional
	Update terra.StringValue `hcl:"update,attr"`
}

type MatchAttributes struct {
	ref terra.Reference
}

func (m MatchAttributes) InternalRef() (terra.Reference, error) {
	return m.ref, nil
}

func (m MatchAttributes) InternalWithRef(ref terra.Reference) MatchAttributes {
	return MatchAttributes{ref: ref}
}

func (m MatchAttributes) InternalTokens() (hclwrite.Tokens, error) {
	return m.ref.InternalTokens()
}

func (m MatchAttributes) DestIpRanges() terra.ListValue[terra.StringValue] {
	return terra.ReferenceAsList[terra.StringValue](m.ref.Append("dest_ip_ranges"))
}

func (m MatchAttributes) SrcIpRanges() terra.ListValue[terra.StringValue] {
	return terra.ReferenceAsList[terra.StringValue](m.ref.Append("src_ip_ranges"))
}

func (m MatchAttributes) Layer4Configs() terra.ListValue[Layer4ConfigsAttributes] {
	return terra.ReferenceAsList[Layer4ConfigsAttributes](m.ref.Append("layer4_configs"))
}

func (m MatchAttributes) SrcSecureTags() terra.ListValue[SrcSecureTagsAttributes] {
	return terra.ReferenceAsList[SrcSecureTagsAttributes](m.ref.Append("src_secure_tags"))
}

type Layer4ConfigsAttributes struct {
	ref terra.Reference
}

func (lc Layer4ConfigsAttributes) InternalRef() (terra.Reference, error) {
	return lc.ref, nil
}

func (lc Layer4ConfigsAttributes) InternalWithRef(ref terra.Reference) Layer4ConfigsAttributes {
	return Layer4ConfigsAttributes{ref: ref}
}

func (lc Layer4ConfigsAttributes) InternalTokens() (hclwrite.Tokens, error) {
	return lc.ref.InternalTokens()
}

func (lc Layer4ConfigsAttributes) IpProtocol() terra.StringValue {
	return terra.ReferenceAsString(lc.ref.Append("ip_protocol"))
}

func (lc Layer4ConfigsAttributes) Ports() terra.ListValue[terra.StringValue] {
	return terra.ReferenceAsList[terra.StringValue](lc.ref.Append("ports"))
}

type SrcSecureTagsAttributes struct {
	ref terra.Reference
}

func (sst SrcSecureTagsAttributes) InternalRef() (terra.Reference, error) {
	return sst.ref, nil
}

func (sst SrcSecureTagsAttributes) InternalWithRef(ref terra.Reference) SrcSecureTagsAttributes {
	return SrcSecureTagsAttributes{ref: ref}
}

func (sst SrcSecureTagsAttributes) InternalTokens() (hclwrite.Tokens, error) {
	return sst.ref.InternalTokens()
}

func (sst SrcSecureTagsAttributes) Name() terra.StringValue {
	return terra.ReferenceAsString(sst.ref.Append("name"))
}

func (sst SrcSecureTagsAttributes) State() terra.StringValue {
	return terra.ReferenceAsString(sst.ref.Append("state"))
}

type TargetSecureTagsAttributes struct {
	ref terra.Reference
}

func (tst TargetSecureTagsAttributes) InternalRef() (terra.Reference, error) {
	return tst.ref, nil
}

func (tst TargetSecureTagsAttributes) InternalWithRef(ref terra.Reference) TargetSecureTagsAttributes {
	return TargetSecureTagsAttributes{ref: ref}
}

func (tst TargetSecureTagsAttributes) InternalTokens() (hclwrite.Tokens, error) {
	return tst.ref.InternalTokens()
}

func (tst TargetSecureTagsAttributes) Name() terra.StringValue {
	return terra.ReferenceAsString(tst.ref.Append("name"))
}

func (tst TargetSecureTagsAttributes) State() terra.StringValue {
	return terra.ReferenceAsString(tst.ref.Append("state"))
}

type TimeoutsAttributes struct {
	ref terra.Reference
}

func (t TimeoutsAttributes) InternalRef() (terra.Reference, error) {
	return t.ref, nil
}

func (t TimeoutsAttributes) InternalWithRef(ref terra.Reference) TimeoutsAttributes {
	return TimeoutsAttributes{ref: ref}
}

func (t TimeoutsAttributes) InternalTokens() (hclwrite.Tokens, error) {
	return t.ref.InternalTokens()
}

func (t TimeoutsAttributes) Create() terra.StringValue {
	return terra.ReferenceAsString(t.ref.Append("create"))
}

func (t TimeoutsAttributes) Delete() terra.StringValue {
	return terra.ReferenceAsString(t.ref.Append("delete"))
}

func (t TimeoutsAttributes) Update() terra.StringValue {
	return terra.ReferenceAsString(t.ref.Append("update"))
}

type MatchState struct {
	DestIpRanges  []string             `json:"dest_ip_ranges"`
	SrcIpRanges   []string             `json:"src_ip_ranges"`
	Layer4Configs []Layer4ConfigsState `json:"layer4_configs"`
	SrcSecureTags []SrcSecureTagsState `json:"src_secure_tags"`
}

type Layer4ConfigsState struct {
	IpProtocol string   `json:"ip_protocol"`
	Ports      []string `json:"ports"`
}

type SrcSecureTagsState struct {
	Name  string `json:"name"`
	State string `json:"state"`
}

type TargetSecureTagsState struct {
	Name  string `json:"name"`
	State string `json:"state"`
}

type TimeoutsState struct {
	Create string `json:"create"`
	Delete string `json:"delete"`
	Update string `json:"update"`
}
