// CODE GENERATED BY github.com/golingon/lingon. DO NOT EDIT.

package azurerm_key_vault

import (
	terra "github.com/golingon/lingon/pkg/terra"
	hclwrite "github.com/hashicorp/hcl/v2/hclwrite"
)

type DataTimeouts struct {
	// Read: string, optional
	Read terra.StringValue `hcl:"read,attr"`
}

type DataAccessPolicyAttributes struct {
	ref terra.Reference
}

func (ap DataAccessPolicyAttributes) InternalRef() (terra.Reference, error) {
	return ap.ref, nil
}

func (ap DataAccessPolicyAttributes) InternalWithRef(ref terra.Reference) DataAccessPolicyAttributes {
	return DataAccessPolicyAttributes{ref: ref}
}

func (ap DataAccessPolicyAttributes) InternalTokens() (hclwrite.Tokens, error) {
	return ap.ref.InternalTokens()
}

func (ap DataAccessPolicyAttributes) ApplicationId() terra.StringValue {
	return terra.ReferenceAsString(ap.ref.Append("application_id"))
}

func (ap DataAccessPolicyAttributes) CertificatePermissions() terra.ListValue[terra.StringValue] {
	return terra.ReferenceAsList[terra.StringValue](ap.ref.Append("certificate_permissions"))
}

func (ap DataAccessPolicyAttributes) KeyPermissions() terra.ListValue[terra.StringValue] {
	return terra.ReferenceAsList[terra.StringValue](ap.ref.Append("key_permissions"))
}

func (ap DataAccessPolicyAttributes) ObjectId() terra.StringValue {
	return terra.ReferenceAsString(ap.ref.Append("object_id"))
}

func (ap DataAccessPolicyAttributes) SecretPermissions() terra.ListValue[terra.StringValue] {
	return terra.ReferenceAsList[terra.StringValue](ap.ref.Append("secret_permissions"))
}

func (ap DataAccessPolicyAttributes) StoragePermissions() terra.ListValue[terra.StringValue] {
	return terra.ReferenceAsList[terra.StringValue](ap.ref.Append("storage_permissions"))
}

func (ap DataAccessPolicyAttributes) TenantId() terra.StringValue {
	return terra.ReferenceAsString(ap.ref.Append("tenant_id"))
}

type DataNetworkAclsAttributes struct {
	ref terra.Reference
}

func (na DataNetworkAclsAttributes) InternalRef() (terra.Reference, error) {
	return na.ref, nil
}

func (na DataNetworkAclsAttributes) InternalWithRef(ref terra.Reference) DataNetworkAclsAttributes {
	return DataNetworkAclsAttributes{ref: ref}
}

func (na DataNetworkAclsAttributes) InternalTokens() (hclwrite.Tokens, error) {
	return na.ref.InternalTokens()
}

func (na DataNetworkAclsAttributes) Bypass() terra.StringValue {
	return terra.ReferenceAsString(na.ref.Append("bypass"))
}

func (na DataNetworkAclsAttributes) DefaultAction() terra.StringValue {
	return terra.ReferenceAsString(na.ref.Append("default_action"))
}

func (na DataNetworkAclsAttributes) IpRules() terra.ListValue[terra.StringValue] {
	return terra.ReferenceAsList[terra.StringValue](na.ref.Append("ip_rules"))
}

func (na DataNetworkAclsAttributes) VirtualNetworkSubnetIds() terra.ListValue[terra.StringValue] {
	return terra.ReferenceAsList[terra.StringValue](na.ref.Append("virtual_network_subnet_ids"))
}

type DataTimeoutsAttributes struct {
	ref terra.Reference
}

func (t DataTimeoutsAttributes) InternalRef() (terra.Reference, error) {
	return t.ref, nil
}

func (t DataTimeoutsAttributes) InternalWithRef(ref terra.Reference) DataTimeoutsAttributes {
	return DataTimeoutsAttributes{ref: ref}
}

func (t DataTimeoutsAttributes) InternalTokens() (hclwrite.Tokens, error) {
	return t.ref.InternalTokens()
}

func (t DataTimeoutsAttributes) Read() terra.StringValue {
	return terra.ReferenceAsString(t.ref.Append("read"))
}

type DataAccessPolicyState struct {
	ApplicationId          string   `json:"application_id"`
	CertificatePermissions []string `json:"certificate_permissions"`
	KeyPermissions         []string `json:"key_permissions"`
	ObjectId               string   `json:"object_id"`
	SecretPermissions      []string `json:"secret_permissions"`
	StoragePermissions     []string `json:"storage_permissions"`
	TenantId               string   `json:"tenant_id"`
}

type DataNetworkAclsState struct {
	Bypass                  string   `json:"bypass"`
	DefaultAction           string   `json:"default_action"`
	IpRules                 []string `json:"ip_rules"`
	VirtualNetworkSubnetIds []string `json:"virtual_network_subnet_ids"`
}

type DataTimeoutsState struct {
	Read string `json:"read"`
}
