// CODE GENERATED BY github.com/golingon/lingon. DO NOT EDIT.

package aws_ssmcontacts_plan

import (
	"encoding/json"
	"fmt"
	"github.com/golingon/lingon/pkg/terra"
	"io"
)

// New creates a new instance of [Resource].
func New(name string, args Args) *Resource {
	return &Resource{
		Args: args,
		Name: name,
	}
}

var _ terra.Resource = (*Resource)(nil)

// Resource represents the Terraform resource aws_ssmcontacts_plan.
type Resource struct {
	Name      string
	Args      Args
	state     *awsSsmcontactsPlanState
	DependsOn terra.Dependencies
	Lifecycle *terra.Lifecycle
}

// Type returns the Terraform object type for [Resource].
func (asp *Resource) Type() string {
	return "aws_ssmcontacts_plan"
}

// LocalName returns the local name for [Resource].
func (asp *Resource) LocalName() string {
	return asp.Name
}

// Configuration returns the configuration (args) for [Resource].
func (asp *Resource) Configuration() interface{} {
	return asp.Args
}

// DependOn is used for other resources to depend on [Resource].
func (asp *Resource) DependOn() terra.Reference {
	return terra.ReferenceResource(asp)
}

// Dependencies returns the list of resources [Resource] depends_on.
func (asp *Resource) Dependencies() terra.Dependencies {
	return asp.DependsOn
}

// LifecycleManagement returns the lifecycle block for [Resource].
func (asp *Resource) LifecycleManagement() *terra.Lifecycle {
	return asp.Lifecycle
}

// Attributes returns the attributes for [Resource].
func (asp *Resource) Attributes() awsSsmcontactsPlanAttributes {
	return awsSsmcontactsPlanAttributes{ref: terra.ReferenceResource(asp)}
}

// ImportState imports the given attribute values into [Resource]'s state.
func (asp *Resource) ImportState(state io.Reader) error {
	asp.state = &awsSsmcontactsPlanState{}
	if err := json.NewDecoder(state).Decode(asp.state); err != nil {
		return fmt.Errorf("decoding state into resource %s.%s: %w", asp.Type(), asp.LocalName(), err)
	}
	return nil
}

// State returns the state and a bool indicating if [Resource] has state.
func (asp *Resource) State() (*awsSsmcontactsPlanState, bool) {
	return asp.state, asp.state != nil
}

// StateMust returns the state for [Resource]. Panics if the state is nil.
func (asp *Resource) StateMust() *awsSsmcontactsPlanState {
	if asp.state == nil {
		panic(fmt.Sprintf("state is nil for resource %s.%s", asp.Type(), asp.LocalName()))
	}
	return asp.state
}

// Args contains the configurations for aws_ssmcontacts_plan.
type Args struct {
	// ContactId: string, required
	ContactId terra.StringValue `hcl:"contact_id,attr" validate:"required"`
	// Id: string, optional
	Id terra.StringValue `hcl:"id,attr"`
	// Stage: min=1
	Stage []Stage `hcl:"stage,block" validate:"min=1"`
}

type awsSsmcontactsPlanAttributes struct {
	ref terra.Reference
}

// ContactId returns a reference to field contact_id of aws_ssmcontacts_plan.
func (asp awsSsmcontactsPlanAttributes) ContactId() terra.StringValue {
	return terra.ReferenceAsString(asp.ref.Append("contact_id"))
}

// Id returns a reference to field id of aws_ssmcontacts_plan.
func (asp awsSsmcontactsPlanAttributes) Id() terra.StringValue {
	return terra.ReferenceAsString(asp.ref.Append("id"))
}

func (asp awsSsmcontactsPlanAttributes) Stage() terra.ListValue[StageAttributes] {
	return terra.ReferenceAsList[StageAttributes](asp.ref.Append("stage"))
}

type awsSsmcontactsPlanState struct {
	ContactId string       `json:"contact_id"`
	Id        string       `json:"id"`
	Stage     []StageState `json:"stage"`
}
