// CODE GENERATED BY github.com/golingon/lingon. DO NOT EDIT.

package aws_ses_receipt_filter

import (
	"encoding/json"
	"fmt"
	"github.com/golingon/lingon/pkg/terra"
	"io"
)

// New creates a new instance of [Resource].
func New(name string, args Args) *Resource {
	return &Resource{
		Args: args,
		Name: name,
	}
}

var _ terra.Resource = (*Resource)(nil)

// Resource represents the Terraform resource aws_ses_receipt_filter.
type Resource struct {
	Name      string
	Args      Args
	state     *awsSesReceiptFilterState
	DependsOn terra.Dependencies
	Lifecycle *terra.Lifecycle
}

// Type returns the Terraform object type for [Resource].
func (asrf *Resource) Type() string {
	return "aws_ses_receipt_filter"
}

// LocalName returns the local name for [Resource].
func (asrf *Resource) LocalName() string {
	return asrf.Name
}

// Configuration returns the configuration (args) for [Resource].
func (asrf *Resource) Configuration() interface{} {
	return asrf.Args
}

// DependOn is used for other resources to depend on [Resource].
func (asrf *Resource) DependOn() terra.Reference {
	return terra.ReferenceResource(asrf)
}

// Dependencies returns the list of resources [Resource] depends_on.
func (asrf *Resource) Dependencies() terra.Dependencies {
	return asrf.DependsOn
}

// LifecycleManagement returns the lifecycle block for [Resource].
func (asrf *Resource) LifecycleManagement() *terra.Lifecycle {
	return asrf.Lifecycle
}

// Attributes returns the attributes for [Resource].
func (asrf *Resource) Attributes() awsSesReceiptFilterAttributes {
	return awsSesReceiptFilterAttributes{ref: terra.ReferenceResource(asrf)}
}

// ImportState imports the given attribute values into [Resource]'s state.
func (asrf *Resource) ImportState(state io.Reader) error {
	asrf.state = &awsSesReceiptFilterState{}
	if err := json.NewDecoder(state).Decode(asrf.state); err != nil {
		return fmt.Errorf("decoding state into resource %s.%s: %w", asrf.Type(), asrf.LocalName(), err)
	}
	return nil
}

// State returns the state and a bool indicating if [Resource] has state.
func (asrf *Resource) State() (*awsSesReceiptFilterState, bool) {
	return asrf.state, asrf.state != nil
}

// StateMust returns the state for [Resource]. Panics if the state is nil.
func (asrf *Resource) StateMust() *awsSesReceiptFilterState {
	if asrf.state == nil {
		panic(fmt.Sprintf("state is nil for resource %s.%s", asrf.Type(), asrf.LocalName()))
	}
	return asrf.state
}

// Args contains the configurations for aws_ses_receipt_filter.
type Args struct {
	// Cidr: string, required
	Cidr terra.StringValue `hcl:"cidr,attr" validate:"required"`
	// Id: string, optional
	Id terra.StringValue `hcl:"id,attr"`
	// Name: string, required
	Name terra.StringValue `hcl:"name,attr" validate:"required"`
	// Policy: string, required
	Policy terra.StringValue `hcl:"policy,attr" validate:"required"`
}

type awsSesReceiptFilterAttributes struct {
	ref terra.Reference
}

// Arn returns a reference to field arn of aws_ses_receipt_filter.
func (asrf awsSesReceiptFilterAttributes) Arn() terra.StringValue {
	return terra.ReferenceAsString(asrf.ref.Append("arn"))
}

// Cidr returns a reference to field cidr of aws_ses_receipt_filter.
func (asrf awsSesReceiptFilterAttributes) Cidr() terra.StringValue {
	return terra.ReferenceAsString(asrf.ref.Append("cidr"))
}

// Id returns a reference to field id of aws_ses_receipt_filter.
func (asrf awsSesReceiptFilterAttributes) Id() terra.StringValue {
	return terra.ReferenceAsString(asrf.ref.Append("id"))
}

// Name returns a reference to field name of aws_ses_receipt_filter.
func (asrf awsSesReceiptFilterAttributes) Name() terra.StringValue {
	return terra.ReferenceAsString(asrf.ref.Append("name"))
}

// Policy returns a reference to field policy of aws_ses_receipt_filter.
func (asrf awsSesReceiptFilterAttributes) Policy() terra.StringValue {
	return terra.ReferenceAsString(asrf.ref.Append("policy"))
}

type awsSesReceiptFilterState struct {
	Arn    string `json:"arn"`
	Cidr   string `json:"cidr"`
	Id     string `json:"id"`
	Name   string `json:"name"`
	Policy string `json:"policy"`
}
