// CODE GENERATED BY github.com/golingon/lingon. DO NOT EDIT.

package google_dataplex_asset_iam_member

import (
	"encoding/json"
	"fmt"
	"github.com/golingon/lingon/pkg/terra"
	"io"
)

// New creates a new instance of [Resource].
func New(name string, args Args) *Resource {
	return &Resource{
		Args: args,
		Name: name,
	}
}

var _ terra.Resource = (*Resource)(nil)

// Resource represents the Terraform resource google_dataplex_asset_iam_member.
type Resource struct {
	Name      string
	Args      Args
	state     *googleDataplexAssetIamMemberState
	DependsOn terra.Dependencies
	Lifecycle *terra.Lifecycle
}

// Type returns the Terraform object type for [Resource].
func (gdaim *Resource) Type() string {
	return "google_dataplex_asset_iam_member"
}

// LocalName returns the local name for [Resource].
func (gdaim *Resource) LocalName() string {
	return gdaim.Name
}

// Configuration returns the configuration (args) for [Resource].
func (gdaim *Resource) Configuration() interface{} {
	return gdaim.Args
}

// DependOn is used for other resources to depend on [Resource].
func (gdaim *Resource) DependOn() terra.Reference {
	return terra.ReferenceResource(gdaim)
}

// Dependencies returns the list of resources [Resource] depends_on.
func (gdaim *Resource) Dependencies() terra.Dependencies {
	return gdaim.DependsOn
}

// LifecycleManagement returns the lifecycle block for [Resource].
func (gdaim *Resource) LifecycleManagement() *terra.Lifecycle {
	return gdaim.Lifecycle
}

// Attributes returns the attributes for [Resource].
func (gdaim *Resource) Attributes() googleDataplexAssetIamMemberAttributes {
	return googleDataplexAssetIamMemberAttributes{ref: terra.ReferenceResource(gdaim)}
}

// ImportState imports the given attribute values into [Resource]'s state.
func (gdaim *Resource) ImportState(state io.Reader) error {
	gdaim.state = &googleDataplexAssetIamMemberState{}
	if err := json.NewDecoder(state).Decode(gdaim.state); err != nil {
		return fmt.Errorf("decoding state into resource %s.%s: %w", gdaim.Type(), gdaim.LocalName(), err)
	}
	return nil
}

// State returns the state and a bool indicating if [Resource] has state.
func (gdaim *Resource) State() (*googleDataplexAssetIamMemberState, bool) {
	return gdaim.state, gdaim.state != nil
}

// StateMust returns the state for [Resource]. Panics if the state is nil.
func (gdaim *Resource) StateMust() *googleDataplexAssetIamMemberState {
	if gdaim.state == nil {
		panic(fmt.Sprintf("state is nil for resource %s.%s", gdaim.Type(), gdaim.LocalName()))
	}
	return gdaim.state
}

// Args contains the configurations for google_dataplex_asset_iam_member.
type Args struct {
	// Asset: string, required
	Asset terra.StringValue `hcl:"asset,attr" validate:"required"`
	// DataplexZone: string, required
	DataplexZone terra.StringValue `hcl:"dataplex_zone,attr" validate:"required"`
	// Id: string, optional
	Id terra.StringValue `hcl:"id,attr"`
	// Lake: string, required
	Lake terra.StringValue `hcl:"lake,attr" validate:"required"`
	// Location: string, optional
	Location terra.StringValue `hcl:"location,attr"`
	// Member: string, required
	Member terra.StringValue `hcl:"member,attr" validate:"required"`
	// Project: string, optional
	Project terra.StringValue `hcl:"project,attr"`
	// Role: string, required
	Role terra.StringValue `hcl:"role,attr" validate:"required"`
	// Condition: optional
	Condition *Condition `hcl:"condition,block"`
}

type googleDataplexAssetIamMemberAttributes struct {
	ref terra.Reference
}

// Asset returns a reference to field asset of google_dataplex_asset_iam_member.
func (gdaim googleDataplexAssetIamMemberAttributes) Asset() terra.StringValue {
	return terra.ReferenceAsString(gdaim.ref.Append("asset"))
}

// DataplexZone returns a reference to field dataplex_zone of google_dataplex_asset_iam_member.
func (gdaim googleDataplexAssetIamMemberAttributes) DataplexZone() terra.StringValue {
	return terra.ReferenceAsString(gdaim.ref.Append("dataplex_zone"))
}

// Etag returns a reference to field etag of google_dataplex_asset_iam_member.
func (gdaim googleDataplexAssetIamMemberAttributes) Etag() terra.StringValue {
	return terra.ReferenceAsString(gdaim.ref.Append("etag"))
}

// Id returns a reference to field id of google_dataplex_asset_iam_member.
func (gdaim googleDataplexAssetIamMemberAttributes) Id() terra.StringValue {
	return terra.ReferenceAsString(gdaim.ref.Append("id"))
}

// Lake returns a reference to field lake of google_dataplex_asset_iam_member.
func (gdaim googleDataplexAssetIamMemberAttributes) Lake() terra.StringValue {
	return terra.ReferenceAsString(gdaim.ref.Append("lake"))
}

// Location returns a reference to field location of google_dataplex_asset_iam_member.
func (gdaim googleDataplexAssetIamMemberAttributes) Location() terra.StringValue {
	return terra.ReferenceAsString(gdaim.ref.Append("location"))
}

// Member returns a reference to field member of google_dataplex_asset_iam_member.
func (gdaim googleDataplexAssetIamMemberAttributes) Member() terra.StringValue {
	return terra.ReferenceAsString(gdaim.ref.Append("member"))
}

// Project returns a reference to field project of google_dataplex_asset_iam_member.
func (gdaim googleDataplexAssetIamMemberAttributes) Project() terra.StringValue {
	return terra.ReferenceAsString(gdaim.ref.Append("project"))
}

// Role returns a reference to field role of google_dataplex_asset_iam_member.
func (gdaim googleDataplexAssetIamMemberAttributes) Role() terra.StringValue {
	return terra.ReferenceAsString(gdaim.ref.Append("role"))
}

func (gdaim googleDataplexAssetIamMemberAttributes) Condition() terra.ListValue[ConditionAttributes] {
	return terra.ReferenceAsList[ConditionAttributes](gdaim.ref.Append("condition"))
}

type googleDataplexAssetIamMemberState struct {
	Asset        string           `json:"asset"`
	DataplexZone string           `json:"dataplex_zone"`
	Etag         string           `json:"etag"`
	Id           string           `json:"id"`
	Lake         string           `json:"lake"`
	Location     string           `json:"location"`
	Member       string           `json:"member"`
	Project      string           `json:"project"`
	Role         string           `json:"role"`
	Condition    []ConditionState `json:"condition"`
}
