// CODE GENERATED BY github.com/golingon/lingon. DO NOT EDIT.

package google_migration_center_preference_set

import (
	"encoding/json"
	"fmt"
	"github.com/golingon/lingon/pkg/terra"
	"io"
)

// New creates a new instance of [Resource].
func New(name string, args Args) *Resource {
	return &Resource{
		Args: args,
		Name: name,
	}
}

var _ terra.Resource = (*Resource)(nil)

// Resource represents the Terraform resource google_migration_center_preference_set.
type Resource struct {
	Name      string
	Args      Args
	state     *googleMigrationCenterPreferenceSetState
	DependsOn terra.Dependencies
	Lifecycle *terra.Lifecycle
}

// Type returns the Terraform object type for [Resource].
func (gmcps *Resource) Type() string {
	return "google_migration_center_preference_set"
}

// LocalName returns the local name for [Resource].
func (gmcps *Resource) LocalName() string {
	return gmcps.Name
}

// Configuration returns the configuration (args) for [Resource].
func (gmcps *Resource) Configuration() interface{} {
	return gmcps.Args
}

// DependOn is used for other resources to depend on [Resource].
func (gmcps *Resource) DependOn() terra.Reference {
	return terra.ReferenceResource(gmcps)
}

// Dependencies returns the list of resources [Resource] depends_on.
func (gmcps *Resource) Dependencies() terra.Dependencies {
	return gmcps.DependsOn
}

// LifecycleManagement returns the lifecycle block for [Resource].
func (gmcps *Resource) LifecycleManagement() *terra.Lifecycle {
	return gmcps.Lifecycle
}

// Attributes returns the attributes for [Resource].
func (gmcps *Resource) Attributes() googleMigrationCenterPreferenceSetAttributes {
	return googleMigrationCenterPreferenceSetAttributes{ref: terra.ReferenceResource(gmcps)}
}

// ImportState imports the given attribute values into [Resource]'s state.
func (gmcps *Resource) ImportState(state io.Reader) error {
	gmcps.state = &googleMigrationCenterPreferenceSetState{}
	if err := json.NewDecoder(state).Decode(gmcps.state); err != nil {
		return fmt.Errorf("decoding state into resource %s.%s: %w", gmcps.Type(), gmcps.LocalName(), err)
	}
	return nil
}

// State returns the state and a bool indicating if [Resource] has state.
func (gmcps *Resource) State() (*googleMigrationCenterPreferenceSetState, bool) {
	return gmcps.state, gmcps.state != nil
}

// StateMust returns the state for [Resource]. Panics if the state is nil.
func (gmcps *Resource) StateMust() *googleMigrationCenterPreferenceSetState {
	if gmcps.state == nil {
		panic(fmt.Sprintf("state is nil for resource %s.%s", gmcps.Type(), gmcps.LocalName()))
	}
	return gmcps.state
}

// Args contains the configurations for google_migration_center_preference_set.
type Args struct {
	// Description: string, optional
	Description terra.StringValue `hcl:"description,attr"`
	// DisplayName: string, optional
	DisplayName terra.StringValue `hcl:"display_name,attr"`
	// Id: string, optional
	Id terra.StringValue `hcl:"id,attr"`
	// Location: string, required
	Location terra.StringValue `hcl:"location,attr" validate:"required"`
	// PreferenceSetId: string, required
	PreferenceSetId terra.StringValue `hcl:"preference_set_id,attr" validate:"required"`
	// Project: string, optional
	Project terra.StringValue `hcl:"project,attr"`
	// Timeouts: optional
	Timeouts *Timeouts `hcl:"timeouts,block"`
	// VirtualMachinePreferences: optional
	VirtualMachinePreferences *VirtualMachinePreferences `hcl:"virtual_machine_preferences,block"`
}

type googleMigrationCenterPreferenceSetAttributes struct {
	ref terra.Reference
}

// CreateTime returns a reference to field create_time of google_migration_center_preference_set.
func (gmcps googleMigrationCenterPreferenceSetAttributes) CreateTime() terra.StringValue {
	return terra.ReferenceAsString(gmcps.ref.Append("create_time"))
}

// Description returns a reference to field description of google_migration_center_preference_set.
func (gmcps googleMigrationCenterPreferenceSetAttributes) Description() terra.StringValue {
	return terra.ReferenceAsString(gmcps.ref.Append("description"))
}

// DisplayName returns a reference to field display_name of google_migration_center_preference_set.
func (gmcps googleMigrationCenterPreferenceSetAttributes) DisplayName() terra.StringValue {
	return terra.ReferenceAsString(gmcps.ref.Append("display_name"))
}

// Id returns a reference to field id of google_migration_center_preference_set.
func (gmcps googleMigrationCenterPreferenceSetAttributes) Id() terra.StringValue {
	return terra.ReferenceAsString(gmcps.ref.Append("id"))
}

// Location returns a reference to field location of google_migration_center_preference_set.
func (gmcps googleMigrationCenterPreferenceSetAttributes) Location() terra.StringValue {
	return terra.ReferenceAsString(gmcps.ref.Append("location"))
}

// Name returns a reference to field name of google_migration_center_preference_set.
func (gmcps googleMigrationCenterPreferenceSetAttributes) Name() terra.StringValue {
	return terra.ReferenceAsString(gmcps.ref.Append("name"))
}

// PreferenceSetId returns a reference to field preference_set_id of google_migration_center_preference_set.
func (gmcps googleMigrationCenterPreferenceSetAttributes) PreferenceSetId() terra.StringValue {
	return terra.ReferenceAsString(gmcps.ref.Append("preference_set_id"))
}

// Project returns a reference to field project of google_migration_center_preference_set.
func (gmcps googleMigrationCenterPreferenceSetAttributes) Project() terra.StringValue {
	return terra.ReferenceAsString(gmcps.ref.Append("project"))
}

// UpdateTime returns a reference to field update_time of google_migration_center_preference_set.
func (gmcps googleMigrationCenterPreferenceSetAttributes) UpdateTime() terra.StringValue {
	return terra.ReferenceAsString(gmcps.ref.Append("update_time"))
}

func (gmcps googleMigrationCenterPreferenceSetAttributes) Timeouts() TimeoutsAttributes {
	return terra.ReferenceAsSingle[TimeoutsAttributes](gmcps.ref.Append("timeouts"))
}

func (gmcps googleMigrationCenterPreferenceSetAttributes) VirtualMachinePreferences() terra.ListValue[VirtualMachinePreferencesAttributes] {
	return terra.ReferenceAsList[VirtualMachinePreferencesAttributes](gmcps.ref.Append("virtual_machine_preferences"))
}

type googleMigrationCenterPreferenceSetState struct {
	CreateTime                string                           `json:"create_time"`
	Description               string                           `json:"description"`
	DisplayName               string                           `json:"display_name"`
	Id                        string                           `json:"id"`
	Location                  string                           `json:"location"`
	Name                      string                           `json:"name"`
	PreferenceSetId           string                           `json:"preference_set_id"`
	Project                   string                           `json:"project"`
	UpdateTime                string                           `json:"update_time"`
	Timeouts                  *TimeoutsState                   `json:"timeouts"`
	VirtualMachinePreferences []VirtualMachinePreferencesState `json:"virtual_machine_preferences"`
}
