// CODE GENERATED BY github.com/golingon/lingon. DO NOT EDIT.

package azurerm_dev_test_lab

import "github.com/golingon/lingon/pkg/terra"

// Data creates a new instance of [DataSource].
func Data(name string, args DataArgs) *DataSource {
	return &DataSource{
		Args: args,
		Name: name,
	}
}

var _ terra.DataSource = (*DataSource)(nil)

// DataSource represents the Terraform data resource azurerm_dev_test_lab.
type DataSource struct {
	Name string
	Args DataArgs
}

// DataSource returns the Terraform object type for [DataSource].
func (adtl *DataSource) DataSource() string {
	return "azurerm_dev_test_lab"
}

// LocalName returns the local name for [DataSource].
func (adtl *DataSource) LocalName() string {
	return adtl.Name
}

// Configuration returns the configuration (args) for [DataSource].
func (adtl *DataSource) Configuration() interface{} {
	return adtl.Args
}

// Attributes returns the attributes for [DataSource].
func (adtl *DataSource) Attributes() dataAzurermDevTestLabAttributes {
	return dataAzurermDevTestLabAttributes{ref: terra.ReferenceDataSource(adtl)}
}

// DataArgs contains the configurations for azurerm_dev_test_lab.
type DataArgs struct {
	// Id: string, optional
	Id terra.StringValue `hcl:"id,attr"`
	// Name: string, required
	Name terra.StringValue `hcl:"name,attr" validate:"required"`
	// ResourceGroupName: string, required
	ResourceGroupName terra.StringValue `hcl:"resource_group_name,attr" validate:"required"`
	// Timeouts: optional
	Timeouts *DataTimeouts `hcl:"timeouts,block"`
}

type dataAzurermDevTestLabAttributes struct {
	ref terra.Reference
}

// ArtifactsStorageAccountId returns a reference to field artifacts_storage_account_id of azurerm_dev_test_lab.
func (adtl dataAzurermDevTestLabAttributes) ArtifactsStorageAccountId() terra.StringValue {
	return terra.ReferenceAsString(adtl.ref.Append("artifacts_storage_account_id"))
}

// DefaultPremiumStorageAccountId returns a reference to field default_premium_storage_account_id of azurerm_dev_test_lab.
func (adtl dataAzurermDevTestLabAttributes) DefaultPremiumStorageAccountId() terra.StringValue {
	return terra.ReferenceAsString(adtl.ref.Append("default_premium_storage_account_id"))
}

// DefaultStorageAccountId returns a reference to field default_storage_account_id of azurerm_dev_test_lab.
func (adtl dataAzurermDevTestLabAttributes) DefaultStorageAccountId() terra.StringValue {
	return terra.ReferenceAsString(adtl.ref.Append("default_storage_account_id"))
}

// Id returns a reference to field id of azurerm_dev_test_lab.
func (adtl dataAzurermDevTestLabAttributes) Id() terra.StringValue {
	return terra.ReferenceAsString(adtl.ref.Append("id"))
}

// KeyVaultId returns a reference to field key_vault_id of azurerm_dev_test_lab.
func (adtl dataAzurermDevTestLabAttributes) KeyVaultId() terra.StringValue {
	return terra.ReferenceAsString(adtl.ref.Append("key_vault_id"))
}

// Location returns a reference to field location of azurerm_dev_test_lab.
func (adtl dataAzurermDevTestLabAttributes) Location() terra.StringValue {
	return terra.ReferenceAsString(adtl.ref.Append("location"))
}

// Name returns a reference to field name of azurerm_dev_test_lab.
func (adtl dataAzurermDevTestLabAttributes) Name() terra.StringValue {
	return terra.ReferenceAsString(adtl.ref.Append("name"))
}

// PremiumDataDiskStorageAccountId returns a reference to field premium_data_disk_storage_account_id of azurerm_dev_test_lab.
func (adtl dataAzurermDevTestLabAttributes) PremiumDataDiskStorageAccountId() terra.StringValue {
	return terra.ReferenceAsString(adtl.ref.Append("premium_data_disk_storage_account_id"))
}

// ResourceGroupName returns a reference to field resource_group_name of azurerm_dev_test_lab.
func (adtl dataAzurermDevTestLabAttributes) ResourceGroupName() terra.StringValue {
	return terra.ReferenceAsString(adtl.ref.Append("resource_group_name"))
}

// StorageType returns a reference to field storage_type of azurerm_dev_test_lab.
func (adtl dataAzurermDevTestLabAttributes) StorageType() terra.StringValue {
	return terra.ReferenceAsString(adtl.ref.Append("storage_type"))
}

// Tags returns a reference to field tags of azurerm_dev_test_lab.
func (adtl dataAzurermDevTestLabAttributes) Tags() terra.MapValue[terra.StringValue] {
	return terra.ReferenceAsMap[terra.StringValue](adtl.ref.Append("tags"))
}

// UniqueIdentifier returns a reference to field unique_identifier of azurerm_dev_test_lab.
func (adtl dataAzurermDevTestLabAttributes) UniqueIdentifier() terra.StringValue {
	return terra.ReferenceAsString(adtl.ref.Append("unique_identifier"))
}

func (adtl dataAzurermDevTestLabAttributes) Timeouts() DataTimeoutsAttributes {
	return terra.ReferenceAsSingle[DataTimeoutsAttributes](adtl.ref.Append("timeouts"))
}
