// CODE GENERATED BY github.com/golingon/lingon. DO NOT EDIT.

package google_api_gateway_api_config

import (
	terra "github.com/golingon/lingon/pkg/terra"
	hclwrite "github.com/hashicorp/hcl/v2/hclwrite"
)

type GatewayConfig struct {
	// GatewayConfigBackendConfig: required
	BackendConfig *GatewayConfigBackendConfig `hcl:"backend_config,block" validate:"required"`
}

type GatewayConfigBackendConfig struct {
	// GoogleServiceAccount: string, required
	GoogleServiceAccount terra.StringValue `hcl:"google_service_account,attr" validate:"required"`
}

type GrpcServices struct {
	// GrpcServicesFileDescriptorSet: required
	FileDescriptorSet *GrpcServicesFileDescriptorSet `hcl:"file_descriptor_set,block" validate:"required"`
	// GrpcServicesSource: min=0
	Source []GrpcServicesSource `hcl:"source,block" validate:"min=0"`
}

type GrpcServicesFileDescriptorSet struct {
	// Contents: string, required
	Contents terra.StringValue `hcl:"contents,attr" validate:"required"`
	// Path: string, required
	Path terra.StringValue `hcl:"path,attr" validate:"required"`
}

type GrpcServicesSource struct {
	// Contents: string, required
	Contents terra.StringValue `hcl:"contents,attr" validate:"required"`
	// Path: string, required
	Path terra.StringValue `hcl:"path,attr" validate:"required"`
}

type ManagedServiceConfigs struct {
	// Contents: string, required
	Contents terra.StringValue `hcl:"contents,attr" validate:"required"`
	// Path: string, required
	Path terra.StringValue `hcl:"path,attr" validate:"required"`
}

type OpenapiDocuments struct {
	// OpenapiDocumentsDocument: required
	Document *OpenapiDocumentsDocument `hcl:"document,block" validate:"required"`
}

type OpenapiDocumentsDocument struct {
	// Contents: string, required
	Contents terra.StringValue `hcl:"contents,attr" validate:"required"`
	// Path: string, required
	Path terra.StringValue `hcl:"path,attr" validate:"required"`
}

type Timeouts struct {
	// Create: string, optional
	Create terra.StringValue `hcl:"create,attr"`
	// Delete: string, optional
	Delete terra.StringValue `hcl:"delete,attr"`
	// Update: string, optional
	Update terra.StringValue `hcl:"update,attr"`
}

type GatewayConfigAttributes struct {
	ref terra.Reference
}

func (gc GatewayConfigAttributes) InternalRef() (terra.Reference, error) {
	return gc.ref, nil
}

func (gc GatewayConfigAttributes) InternalWithRef(ref terra.Reference) GatewayConfigAttributes {
	return GatewayConfigAttributes{ref: ref}
}

func (gc GatewayConfigAttributes) InternalTokens() (hclwrite.Tokens, error) {
	return gc.ref.InternalTokens()
}

func (gc GatewayConfigAttributes) BackendConfig() terra.ListValue[GatewayConfigBackendConfigAttributes] {
	return terra.ReferenceAsList[GatewayConfigBackendConfigAttributes](gc.ref.Append("backend_config"))
}

type GatewayConfigBackendConfigAttributes struct {
	ref terra.Reference
}

func (bc GatewayConfigBackendConfigAttributes) InternalRef() (terra.Reference, error) {
	return bc.ref, nil
}

func (bc GatewayConfigBackendConfigAttributes) InternalWithRef(ref terra.Reference) GatewayConfigBackendConfigAttributes {
	return GatewayConfigBackendConfigAttributes{ref: ref}
}

func (bc GatewayConfigBackendConfigAttributes) InternalTokens() (hclwrite.Tokens, error) {
	return bc.ref.InternalTokens()
}

func (bc GatewayConfigBackendConfigAttributes) GoogleServiceAccount() terra.StringValue {
	return terra.ReferenceAsString(bc.ref.Append("google_service_account"))
}

type GrpcServicesAttributes struct {
	ref terra.Reference
}

func (gs GrpcServicesAttributes) InternalRef() (terra.Reference, error) {
	return gs.ref, nil
}

func (gs GrpcServicesAttributes) InternalWithRef(ref terra.Reference) GrpcServicesAttributes {
	return GrpcServicesAttributes{ref: ref}
}

func (gs GrpcServicesAttributes) InternalTokens() (hclwrite.Tokens, error) {
	return gs.ref.InternalTokens()
}

func (gs GrpcServicesAttributes) FileDescriptorSet() terra.ListValue[GrpcServicesFileDescriptorSetAttributes] {
	return terra.ReferenceAsList[GrpcServicesFileDescriptorSetAttributes](gs.ref.Append("file_descriptor_set"))
}

func (gs GrpcServicesAttributes) Source() terra.ListValue[GrpcServicesSourceAttributes] {
	return terra.ReferenceAsList[GrpcServicesSourceAttributes](gs.ref.Append("source"))
}

type GrpcServicesFileDescriptorSetAttributes struct {
	ref terra.Reference
}

func (fds GrpcServicesFileDescriptorSetAttributes) InternalRef() (terra.Reference, error) {
	return fds.ref, nil
}

func (fds GrpcServicesFileDescriptorSetAttributes) InternalWithRef(ref terra.Reference) GrpcServicesFileDescriptorSetAttributes {
	return GrpcServicesFileDescriptorSetAttributes{ref: ref}
}

func (fds GrpcServicesFileDescriptorSetAttributes) InternalTokens() (hclwrite.Tokens, error) {
	return fds.ref.InternalTokens()
}

func (fds GrpcServicesFileDescriptorSetAttributes) Contents() terra.StringValue {
	return terra.ReferenceAsString(fds.ref.Append("contents"))
}

func (fds GrpcServicesFileDescriptorSetAttributes) Path() terra.StringValue {
	return terra.ReferenceAsString(fds.ref.Append("path"))
}

type GrpcServicesSourceAttributes struct {
	ref terra.Reference
}

func (s GrpcServicesSourceAttributes) InternalRef() (terra.Reference, error) {
	return s.ref, nil
}

func (s GrpcServicesSourceAttributes) InternalWithRef(ref terra.Reference) GrpcServicesSourceAttributes {
	return GrpcServicesSourceAttributes{ref: ref}
}

func (s GrpcServicesSourceAttributes) InternalTokens() (hclwrite.Tokens, error) {
	return s.ref.InternalTokens()
}

func (s GrpcServicesSourceAttributes) Contents() terra.StringValue {
	return terra.ReferenceAsString(s.ref.Append("contents"))
}

func (s GrpcServicesSourceAttributes) Path() terra.StringValue {
	return terra.ReferenceAsString(s.ref.Append("path"))
}

type ManagedServiceConfigsAttributes struct {
	ref terra.Reference
}

func (msc ManagedServiceConfigsAttributes) InternalRef() (terra.Reference, error) {
	return msc.ref, nil
}

func (msc ManagedServiceConfigsAttributes) InternalWithRef(ref terra.Reference) ManagedServiceConfigsAttributes {
	return ManagedServiceConfigsAttributes{ref: ref}
}

func (msc ManagedServiceConfigsAttributes) InternalTokens() (hclwrite.Tokens, error) {
	return msc.ref.InternalTokens()
}

func (msc ManagedServiceConfigsAttributes) Contents() terra.StringValue {
	return terra.ReferenceAsString(msc.ref.Append("contents"))
}

func (msc ManagedServiceConfigsAttributes) Path() terra.StringValue {
	return terra.ReferenceAsString(msc.ref.Append("path"))
}

type OpenapiDocumentsAttributes struct {
	ref terra.Reference
}

func (od OpenapiDocumentsAttributes) InternalRef() (terra.Reference, error) {
	return od.ref, nil
}

func (od OpenapiDocumentsAttributes) InternalWithRef(ref terra.Reference) OpenapiDocumentsAttributes {
	return OpenapiDocumentsAttributes{ref: ref}
}

func (od OpenapiDocumentsAttributes) InternalTokens() (hclwrite.Tokens, error) {
	return od.ref.InternalTokens()
}

func (od OpenapiDocumentsAttributes) Document() terra.ListValue[OpenapiDocumentsDocumentAttributes] {
	return terra.ReferenceAsList[OpenapiDocumentsDocumentAttributes](od.ref.Append("document"))
}

type OpenapiDocumentsDocumentAttributes struct {
	ref terra.Reference
}

func (d OpenapiDocumentsDocumentAttributes) InternalRef() (terra.Reference, error) {
	return d.ref, nil
}

func (d OpenapiDocumentsDocumentAttributes) InternalWithRef(ref terra.Reference) OpenapiDocumentsDocumentAttributes {
	return OpenapiDocumentsDocumentAttributes{ref: ref}
}

func (d OpenapiDocumentsDocumentAttributes) InternalTokens() (hclwrite.Tokens, error) {
	return d.ref.InternalTokens()
}

func (d OpenapiDocumentsDocumentAttributes) Contents() terra.StringValue {
	return terra.ReferenceAsString(d.ref.Append("contents"))
}

func (d OpenapiDocumentsDocumentAttributes) Path() terra.StringValue {
	return terra.ReferenceAsString(d.ref.Append("path"))
}

type TimeoutsAttributes struct {
	ref terra.Reference
}

func (t TimeoutsAttributes) InternalRef() (terra.Reference, error) {
	return t.ref, nil
}

func (t TimeoutsAttributes) InternalWithRef(ref terra.Reference) TimeoutsAttributes {
	return TimeoutsAttributes{ref: ref}
}

func (t TimeoutsAttributes) InternalTokens() (hclwrite.Tokens, error) {
	return t.ref.InternalTokens()
}

func (t TimeoutsAttributes) Create() terra.StringValue {
	return terra.ReferenceAsString(t.ref.Append("create"))
}

func (t TimeoutsAttributes) Delete() terra.StringValue {
	return terra.ReferenceAsString(t.ref.Append("delete"))
}

func (t TimeoutsAttributes) Update() terra.StringValue {
	return terra.ReferenceAsString(t.ref.Append("update"))
}

type GatewayConfigState struct {
	BackendConfig []GatewayConfigBackendConfigState `json:"backend_config"`
}

type GatewayConfigBackendConfigState struct {
	GoogleServiceAccount string `json:"google_service_account"`
}

type GrpcServicesState struct {
	FileDescriptorSet []GrpcServicesFileDescriptorSetState `json:"file_descriptor_set"`
	Source            []GrpcServicesSourceState            `json:"source"`
}

type GrpcServicesFileDescriptorSetState struct {
	Contents string `json:"contents"`
	Path     string `json:"path"`
}

type GrpcServicesSourceState struct {
	Contents string `json:"contents"`
	Path     string `json:"path"`
}

type ManagedServiceConfigsState struct {
	Contents string `json:"contents"`
	Path     string `json:"path"`
}

type OpenapiDocumentsState struct {
	Document []OpenapiDocumentsDocumentState `json:"document"`
}

type OpenapiDocumentsDocumentState struct {
	Contents string `json:"contents"`
	Path     string `json:"path"`
}

type TimeoutsState struct {
	Create string `json:"create"`
	Delete string `json:"delete"`
	Update string `json:"update"`
}
