// CODE GENERATED BY github.com/golingon/lingon. DO NOT EDIT.

package google_clouddeploy_custom_target_type_iam_policy

import (
	"encoding/json"
	"fmt"
	"github.com/golingon/lingon/pkg/terra"
	"io"
)

// New creates a new instance of [Resource].
func New(name string, args Args) *Resource {
	return &Resource{
		Args: args,
		Name: name,
	}
}

var _ terra.Resource = (*Resource)(nil)

// Resource represents the Terraform resource google_clouddeploy_custom_target_type_iam_policy.
type Resource struct {
	Name      string
	Args      Args
	state     *googleClouddeployCustomTargetTypeIamPolicyState
	DependsOn terra.Dependencies
	Lifecycle *terra.Lifecycle
}

// Type returns the Terraform object type for [Resource].
func (gccttip *Resource) Type() string {
	return "google_clouddeploy_custom_target_type_iam_policy"
}

// LocalName returns the local name for [Resource].
func (gccttip *Resource) LocalName() string {
	return gccttip.Name
}

// Configuration returns the configuration (args) for [Resource].
func (gccttip *Resource) Configuration() interface{} {
	return gccttip.Args
}

// DependOn is used for other resources to depend on [Resource].
func (gccttip *Resource) DependOn() terra.Reference {
	return terra.ReferenceResource(gccttip)
}

// Dependencies returns the list of resources [Resource] depends_on.
func (gccttip *Resource) Dependencies() terra.Dependencies {
	return gccttip.DependsOn
}

// LifecycleManagement returns the lifecycle block for [Resource].
func (gccttip *Resource) LifecycleManagement() *terra.Lifecycle {
	return gccttip.Lifecycle
}

// Attributes returns the attributes for [Resource].
func (gccttip *Resource) Attributes() googleClouddeployCustomTargetTypeIamPolicyAttributes {
	return googleClouddeployCustomTargetTypeIamPolicyAttributes{ref: terra.ReferenceResource(gccttip)}
}

// ImportState imports the given attribute values into [Resource]'s state.
func (gccttip *Resource) ImportState(state io.Reader) error {
	gccttip.state = &googleClouddeployCustomTargetTypeIamPolicyState{}
	if err := json.NewDecoder(state).Decode(gccttip.state); err != nil {
		return fmt.Errorf("decoding state into resource %s.%s: %w", gccttip.Type(), gccttip.LocalName(), err)
	}
	return nil
}

// State returns the state and a bool indicating if [Resource] has state.
func (gccttip *Resource) State() (*googleClouddeployCustomTargetTypeIamPolicyState, bool) {
	return gccttip.state, gccttip.state != nil
}

// StateMust returns the state for [Resource]. Panics if the state is nil.
func (gccttip *Resource) StateMust() *googleClouddeployCustomTargetTypeIamPolicyState {
	if gccttip.state == nil {
		panic(fmt.Sprintf("state is nil for resource %s.%s", gccttip.Type(), gccttip.LocalName()))
	}
	return gccttip.state
}

// Args contains the configurations for google_clouddeploy_custom_target_type_iam_policy.
type Args struct {
	// Id: string, optional
	Id terra.StringValue `hcl:"id,attr"`
	// Location: string, optional
	Location terra.StringValue `hcl:"location,attr"`
	// Name: string, required
	Name terra.StringValue `hcl:"name,attr" validate:"required"`
	// PolicyData: string, required
	PolicyData terra.StringValue `hcl:"policy_data,attr" validate:"required"`
	// Project: string, optional
	Project terra.StringValue `hcl:"project,attr"`
}

type googleClouddeployCustomTargetTypeIamPolicyAttributes struct {
	ref terra.Reference
}

// Etag returns a reference to field etag of google_clouddeploy_custom_target_type_iam_policy.
func (gccttip googleClouddeployCustomTargetTypeIamPolicyAttributes) Etag() terra.StringValue {
	return terra.ReferenceAsString(gccttip.ref.Append("etag"))
}

// Id returns a reference to field id of google_clouddeploy_custom_target_type_iam_policy.
func (gccttip googleClouddeployCustomTargetTypeIamPolicyAttributes) Id() terra.StringValue {
	return terra.ReferenceAsString(gccttip.ref.Append("id"))
}

// Location returns a reference to field location of google_clouddeploy_custom_target_type_iam_policy.
func (gccttip googleClouddeployCustomTargetTypeIamPolicyAttributes) Location() terra.StringValue {
	return terra.ReferenceAsString(gccttip.ref.Append("location"))
}

// Name returns a reference to field name of google_clouddeploy_custom_target_type_iam_policy.
func (gccttip googleClouddeployCustomTargetTypeIamPolicyAttributes) Name() terra.StringValue {
	return terra.ReferenceAsString(gccttip.ref.Append("name"))
}

// PolicyData returns a reference to field policy_data of google_clouddeploy_custom_target_type_iam_policy.
func (gccttip googleClouddeployCustomTargetTypeIamPolicyAttributes) PolicyData() terra.StringValue {
	return terra.ReferenceAsString(gccttip.ref.Append("policy_data"))
}

// Project returns a reference to field project of google_clouddeploy_custom_target_type_iam_policy.
func (gccttip googleClouddeployCustomTargetTypeIamPolicyAttributes) Project() terra.StringValue {
	return terra.ReferenceAsString(gccttip.ref.Append("project"))
}

type googleClouddeployCustomTargetTypeIamPolicyState struct {
	Etag       string `json:"etag"`
	Id         string `json:"id"`
	Location   string `json:"location"`
	Name       string `json:"name"`
	PolicyData string `json:"policy_data"`
	Project    string `json:"project"`
}
