// CODE GENERATED BY github.com/golingon/lingon. DO NOT EDIT.

package aws_autoscaling_groups

import "github.com/golingon/lingon/pkg/terra"

// Data creates a new instance of [DataSource].
func Data(name string, args DataArgs) *DataSource {
	return &DataSource{
		Args: args,
		Name: name,
	}
}

var _ terra.DataSource = (*DataSource)(nil)

// DataSource represents the Terraform data resource aws_autoscaling_groups.
type DataSource struct {
	Name string
	Args DataArgs
}

// DataSource returns the Terraform object type for [DataSource].
func (aag *DataSource) DataSource() string {
	return "aws_autoscaling_groups"
}

// LocalName returns the local name for [DataSource].
func (aag *DataSource) LocalName() string {
	return aag.Name
}

// Configuration returns the configuration (args) for [DataSource].
func (aag *DataSource) Configuration() interface{} {
	return aag.Args
}

// Attributes returns the attributes for [DataSource].
func (aag *DataSource) Attributes() dataAwsAutoscalingGroupsAttributes {
	return dataAwsAutoscalingGroupsAttributes{ref: terra.ReferenceDataSource(aag)}
}

// DataArgs contains the configurations for aws_autoscaling_groups.
type DataArgs struct {
	// Id: string, optional
	Id terra.StringValue `hcl:"id,attr"`
	// Names: list of string, optional
	Names terra.ListValue[terra.StringValue] `hcl:"names,attr"`
	// Filter: min=0
	Filter []DataFilter `hcl:"filter,block" validate:"min=0"`
}

type dataAwsAutoscalingGroupsAttributes struct {
	ref terra.Reference
}

// Arns returns a reference to field arns of aws_autoscaling_groups.
func (aag dataAwsAutoscalingGroupsAttributes) Arns() terra.ListValue[terra.StringValue] {
	return terra.ReferenceAsList[terra.StringValue](aag.ref.Append("arns"))
}

// Id returns a reference to field id of aws_autoscaling_groups.
func (aag dataAwsAutoscalingGroupsAttributes) Id() terra.StringValue {
	return terra.ReferenceAsString(aag.ref.Append("id"))
}

// Names returns a reference to field names of aws_autoscaling_groups.
func (aag dataAwsAutoscalingGroupsAttributes) Names() terra.ListValue[terra.StringValue] {
	return terra.ReferenceAsList[terra.StringValue](aag.ref.Append("names"))
}

func (aag dataAwsAutoscalingGroupsAttributes) Filter() terra.SetValue[DataFilterAttributes] {
	return terra.ReferenceAsSet[DataFilterAttributes](aag.ref.Append("filter"))
}
