// CODE GENERATED BY github.com/golingon/lingon. DO NOT EDIT.

package google_healthcare_hl7_v2_store_iam_policy

import (
	"encoding/json"
	"fmt"
	"github.com/golingon/lingon/pkg/terra"
	"io"
)

// New creates a new instance of [Resource].
func New(name string, args Args) *Resource {
	return &Resource{
		Args: args,
		Name: name,
	}
}

var _ terra.Resource = (*Resource)(nil)

// Resource represents the Terraform resource google_healthcare_hl7_v2_store_iam_policy.
type Resource struct {
	Name      string
	Args      Args
	state     *googleHealthcareHl7V2StoreIamPolicyState
	DependsOn terra.Dependencies
	Lifecycle *terra.Lifecycle
}

// Type returns the Terraform object type for [Resource].
func (ghhvsip *Resource) Type() string {
	return "google_healthcare_hl7_v2_store_iam_policy"
}

// LocalName returns the local name for [Resource].
func (ghhvsip *Resource) LocalName() string {
	return ghhvsip.Name
}

// Configuration returns the configuration (args) for [Resource].
func (ghhvsip *Resource) Configuration() interface{} {
	return ghhvsip.Args
}

// DependOn is used for other resources to depend on [Resource].
func (ghhvsip *Resource) DependOn() terra.Reference {
	return terra.ReferenceResource(ghhvsip)
}

// Dependencies returns the list of resources [Resource] depends_on.
func (ghhvsip *Resource) Dependencies() terra.Dependencies {
	return ghhvsip.DependsOn
}

// LifecycleManagement returns the lifecycle block for [Resource].
func (ghhvsip *Resource) LifecycleManagement() *terra.Lifecycle {
	return ghhvsip.Lifecycle
}

// Attributes returns the attributes for [Resource].
func (ghhvsip *Resource) Attributes() googleHealthcareHl7V2StoreIamPolicyAttributes {
	return googleHealthcareHl7V2StoreIamPolicyAttributes{ref: terra.ReferenceResource(ghhvsip)}
}

// ImportState imports the given attribute values into [Resource]'s state.
func (ghhvsip *Resource) ImportState(state io.Reader) error {
	ghhvsip.state = &googleHealthcareHl7V2StoreIamPolicyState{}
	if err := json.NewDecoder(state).Decode(ghhvsip.state); err != nil {
		return fmt.Errorf("decoding state into resource %s.%s: %w", ghhvsip.Type(), ghhvsip.LocalName(), err)
	}
	return nil
}

// State returns the state and a bool indicating if [Resource] has state.
func (ghhvsip *Resource) State() (*googleHealthcareHl7V2StoreIamPolicyState, bool) {
	return ghhvsip.state, ghhvsip.state != nil
}

// StateMust returns the state for [Resource]. Panics if the state is nil.
func (ghhvsip *Resource) StateMust() *googleHealthcareHl7V2StoreIamPolicyState {
	if ghhvsip.state == nil {
		panic(fmt.Sprintf("state is nil for resource %s.%s", ghhvsip.Type(), ghhvsip.LocalName()))
	}
	return ghhvsip.state
}

// Args contains the configurations for google_healthcare_hl7_v2_store_iam_policy.
type Args struct {
	// Hl7V2StoreId: string, required
	Hl7V2StoreId terra.StringValue `hcl:"hl7_v2_store_id,attr" validate:"required"`
	// Id: string, optional
	Id terra.StringValue `hcl:"id,attr"`
	// PolicyData: string, required
	PolicyData terra.StringValue `hcl:"policy_data,attr" validate:"required"`
}

type googleHealthcareHl7V2StoreIamPolicyAttributes struct {
	ref terra.Reference
}

// Etag returns a reference to field etag of google_healthcare_hl7_v2_store_iam_policy.
func (ghhvsip googleHealthcareHl7V2StoreIamPolicyAttributes) Etag() terra.StringValue {
	return terra.ReferenceAsString(ghhvsip.ref.Append("etag"))
}

// Hl7V2StoreId returns a reference to field hl7_v2_store_id of google_healthcare_hl7_v2_store_iam_policy.
func (ghhvsip googleHealthcareHl7V2StoreIamPolicyAttributes) Hl7V2StoreId() terra.StringValue {
	return terra.ReferenceAsString(ghhvsip.ref.Append("hl7_v2_store_id"))
}

// Id returns a reference to field id of google_healthcare_hl7_v2_store_iam_policy.
func (ghhvsip googleHealthcareHl7V2StoreIamPolicyAttributes) Id() terra.StringValue {
	return terra.ReferenceAsString(ghhvsip.ref.Append("id"))
}

// PolicyData returns a reference to field policy_data of google_healthcare_hl7_v2_store_iam_policy.
func (ghhvsip googleHealthcareHl7V2StoreIamPolicyAttributes) PolicyData() terra.StringValue {
	return terra.ReferenceAsString(ghhvsip.ref.Append("policy_data"))
}

type googleHealthcareHl7V2StoreIamPolicyState struct {
	Etag         string `json:"etag"`
	Hl7V2StoreId string `json:"hl7_v2_store_id"`
	Id           string `json:"id"`
	PolicyData   string `json:"policy_data"`
}
