// CODE GENERATED BY github.com/golingon/lingon. DO NOT EDIT.

package aws_docdb_global_cluster

import (
	"encoding/json"
	"fmt"
	"github.com/golingon/lingon/pkg/terra"
	"io"
)

// New creates a new instance of [Resource].
func New(name string, args Args) *Resource {
	return &Resource{
		Args: args,
		Name: name,
	}
}

var _ terra.Resource = (*Resource)(nil)

// Resource represents the Terraform resource aws_docdb_global_cluster.
type Resource struct {
	Name      string
	Args      Args
	state     *awsDocdbGlobalClusterState
	DependsOn terra.Dependencies
	Lifecycle *terra.Lifecycle
}

// Type returns the Terraform object type for [Resource].
func (adgc *Resource) Type() string {
	return "aws_docdb_global_cluster"
}

// LocalName returns the local name for [Resource].
func (adgc *Resource) LocalName() string {
	return adgc.Name
}

// Configuration returns the configuration (args) for [Resource].
func (adgc *Resource) Configuration() interface{} {
	return adgc.Args
}

// DependOn is used for other resources to depend on [Resource].
func (adgc *Resource) DependOn() terra.Reference {
	return terra.ReferenceResource(adgc)
}

// Dependencies returns the list of resources [Resource] depends_on.
func (adgc *Resource) Dependencies() terra.Dependencies {
	return adgc.DependsOn
}

// LifecycleManagement returns the lifecycle block for [Resource].
func (adgc *Resource) LifecycleManagement() *terra.Lifecycle {
	return adgc.Lifecycle
}

// Attributes returns the attributes for [Resource].
func (adgc *Resource) Attributes() awsDocdbGlobalClusterAttributes {
	return awsDocdbGlobalClusterAttributes{ref: terra.ReferenceResource(adgc)}
}

// ImportState imports the given attribute values into [Resource]'s state.
func (adgc *Resource) ImportState(state io.Reader) error {
	adgc.state = &awsDocdbGlobalClusterState{}
	if err := json.NewDecoder(state).Decode(adgc.state); err != nil {
		return fmt.Errorf("decoding state into resource %s.%s: %w", adgc.Type(), adgc.LocalName(), err)
	}
	return nil
}

// State returns the state and a bool indicating if [Resource] has state.
func (adgc *Resource) State() (*awsDocdbGlobalClusterState, bool) {
	return adgc.state, adgc.state != nil
}

// StateMust returns the state for [Resource]. Panics if the state is nil.
func (adgc *Resource) StateMust() *awsDocdbGlobalClusterState {
	if adgc.state == nil {
		panic(fmt.Sprintf("state is nil for resource %s.%s", adgc.Type(), adgc.LocalName()))
	}
	return adgc.state
}

// Args contains the configurations for aws_docdb_global_cluster.
type Args struct {
	// DatabaseName: string, optional
	DatabaseName terra.StringValue `hcl:"database_name,attr"`
	// DeletionProtection: bool, optional
	DeletionProtection terra.BoolValue `hcl:"deletion_protection,attr"`
	// Engine: string, optional
	Engine terra.StringValue `hcl:"engine,attr"`
	// EngineVersion: string, optional
	EngineVersion terra.StringValue `hcl:"engine_version,attr"`
	// GlobalClusterIdentifier: string, required
	GlobalClusterIdentifier terra.StringValue `hcl:"global_cluster_identifier,attr" validate:"required"`
	// Id: string, optional
	Id terra.StringValue `hcl:"id,attr"`
	// SourceDbClusterIdentifier: string, optional
	SourceDbClusterIdentifier terra.StringValue `hcl:"source_db_cluster_identifier,attr"`
	// StorageEncrypted: bool, optional
	StorageEncrypted terra.BoolValue `hcl:"storage_encrypted,attr"`
	// Timeouts: optional
	Timeouts *Timeouts `hcl:"timeouts,block"`
}

type awsDocdbGlobalClusterAttributes struct {
	ref terra.Reference
}

// Arn returns a reference to field arn of aws_docdb_global_cluster.
func (adgc awsDocdbGlobalClusterAttributes) Arn() terra.StringValue {
	return terra.ReferenceAsString(adgc.ref.Append("arn"))
}

// DatabaseName returns a reference to field database_name of aws_docdb_global_cluster.
func (adgc awsDocdbGlobalClusterAttributes) DatabaseName() terra.StringValue {
	return terra.ReferenceAsString(adgc.ref.Append("database_name"))
}

// DeletionProtection returns a reference to field deletion_protection of aws_docdb_global_cluster.
func (adgc awsDocdbGlobalClusterAttributes) DeletionProtection() terra.BoolValue {
	return terra.ReferenceAsBool(adgc.ref.Append("deletion_protection"))
}

// Engine returns a reference to field engine of aws_docdb_global_cluster.
func (adgc awsDocdbGlobalClusterAttributes) Engine() terra.StringValue {
	return terra.ReferenceAsString(adgc.ref.Append("engine"))
}

// EngineVersion returns a reference to field engine_version of aws_docdb_global_cluster.
func (adgc awsDocdbGlobalClusterAttributes) EngineVersion() terra.StringValue {
	return terra.ReferenceAsString(adgc.ref.Append("engine_version"))
}

// GlobalClusterIdentifier returns a reference to field global_cluster_identifier of aws_docdb_global_cluster.
func (adgc awsDocdbGlobalClusterAttributes) GlobalClusterIdentifier() terra.StringValue {
	return terra.ReferenceAsString(adgc.ref.Append("global_cluster_identifier"))
}

// GlobalClusterResourceId returns a reference to field global_cluster_resource_id of aws_docdb_global_cluster.
func (adgc awsDocdbGlobalClusterAttributes) GlobalClusterResourceId() terra.StringValue {
	return terra.ReferenceAsString(adgc.ref.Append("global_cluster_resource_id"))
}

// Id returns a reference to field id of aws_docdb_global_cluster.
func (adgc awsDocdbGlobalClusterAttributes) Id() terra.StringValue {
	return terra.ReferenceAsString(adgc.ref.Append("id"))
}

// SourceDbClusterIdentifier returns a reference to field source_db_cluster_identifier of aws_docdb_global_cluster.
func (adgc awsDocdbGlobalClusterAttributes) SourceDbClusterIdentifier() terra.StringValue {
	return terra.ReferenceAsString(adgc.ref.Append("source_db_cluster_identifier"))
}

// Status returns a reference to field status of aws_docdb_global_cluster.
func (adgc awsDocdbGlobalClusterAttributes) Status() terra.StringValue {
	return terra.ReferenceAsString(adgc.ref.Append("status"))
}

// StorageEncrypted returns a reference to field storage_encrypted of aws_docdb_global_cluster.
func (adgc awsDocdbGlobalClusterAttributes) StorageEncrypted() terra.BoolValue {
	return terra.ReferenceAsBool(adgc.ref.Append("storage_encrypted"))
}

func (adgc awsDocdbGlobalClusterAttributes) GlobalClusterMembers() terra.SetValue[GlobalClusterMembersAttributes] {
	return terra.ReferenceAsSet[GlobalClusterMembersAttributes](adgc.ref.Append("global_cluster_members"))
}

func (adgc awsDocdbGlobalClusterAttributes) Timeouts() TimeoutsAttributes {
	return terra.ReferenceAsSingle[TimeoutsAttributes](adgc.ref.Append("timeouts"))
}

type awsDocdbGlobalClusterState struct {
	Arn                       string                      `json:"arn"`
	DatabaseName              string                      `json:"database_name"`
	DeletionProtection        bool                        `json:"deletion_protection"`
	Engine                    string                      `json:"engine"`
	EngineVersion             string                      `json:"engine_version"`
	GlobalClusterIdentifier   string                      `json:"global_cluster_identifier"`
	GlobalClusterResourceId   string                      `json:"global_cluster_resource_id"`
	Id                        string                      `json:"id"`
	SourceDbClusterIdentifier string                      `json:"source_db_cluster_identifier"`
	Status                    string                      `json:"status"`
	StorageEncrypted          bool                        `json:"storage_encrypted"`
	GlobalClusterMembers      []GlobalClusterMembersState `json:"global_cluster_members"`
	Timeouts                  *TimeoutsState              `json:"timeouts"`
}
