// CODE GENERATED BY github.com/golingon/lingon. DO NOT EDIT.

package azurerm_sql_failover_group

import (
	"encoding/json"
	"fmt"
	"github.com/golingon/lingon/pkg/terra"
	"io"
)

// New creates a new instance of [Resource].
func New(name string, args Args) *Resource {
	return &Resource{
		Args: args,
		Name: name,
	}
}

var _ terra.Resource = (*Resource)(nil)

// Resource represents the Terraform resource azurerm_sql_failover_group.
type Resource struct {
	Name      string
	Args      Args
	state     *azurermSqlFailoverGroupState
	DependsOn terra.Dependencies
	Lifecycle *terra.Lifecycle
}

// Type returns the Terraform object type for [Resource].
func (asfg *Resource) Type() string {
	return "azurerm_sql_failover_group"
}

// LocalName returns the local name for [Resource].
func (asfg *Resource) LocalName() string {
	return asfg.Name
}

// Configuration returns the configuration (args) for [Resource].
func (asfg *Resource) Configuration() interface{} {
	return asfg.Args
}

// DependOn is used for other resources to depend on [Resource].
func (asfg *Resource) DependOn() terra.Reference {
	return terra.ReferenceResource(asfg)
}

// Dependencies returns the list of resources [Resource] depends_on.
func (asfg *Resource) Dependencies() terra.Dependencies {
	return asfg.DependsOn
}

// LifecycleManagement returns the lifecycle block for [Resource].
func (asfg *Resource) LifecycleManagement() *terra.Lifecycle {
	return asfg.Lifecycle
}

// Attributes returns the attributes for [Resource].
func (asfg *Resource) Attributes() azurermSqlFailoverGroupAttributes {
	return azurermSqlFailoverGroupAttributes{ref: terra.ReferenceResource(asfg)}
}

// ImportState imports the given attribute values into [Resource]'s state.
func (asfg *Resource) ImportState(state io.Reader) error {
	asfg.state = &azurermSqlFailoverGroupState{}
	if err := json.NewDecoder(state).Decode(asfg.state); err != nil {
		return fmt.Errorf("decoding state into resource %s.%s: %w", asfg.Type(), asfg.LocalName(), err)
	}
	return nil
}

// State returns the state and a bool indicating if [Resource] has state.
func (asfg *Resource) State() (*azurermSqlFailoverGroupState, bool) {
	return asfg.state, asfg.state != nil
}

// StateMust returns the state for [Resource]. Panics if the state is nil.
func (asfg *Resource) StateMust() *azurermSqlFailoverGroupState {
	if asfg.state == nil {
		panic(fmt.Sprintf("state is nil for resource %s.%s", asfg.Type(), asfg.LocalName()))
	}
	return asfg.state
}

// Args contains the configurations for azurerm_sql_failover_group.
type Args struct {
	// Databases: set of string, optional
	Databases terra.SetValue[terra.StringValue] `hcl:"databases,attr"`
	// Id: string, optional
	Id terra.StringValue `hcl:"id,attr"`
	// Name: string, required
	Name terra.StringValue `hcl:"name,attr" validate:"required"`
	// ResourceGroupName: string, required
	ResourceGroupName terra.StringValue `hcl:"resource_group_name,attr" validate:"required"`
	// ServerName: string, required
	ServerName terra.StringValue `hcl:"server_name,attr" validate:"required"`
	// Tags: map of string, optional
	Tags terra.MapValue[terra.StringValue] `hcl:"tags,attr"`
	// PartnerServers: min=1
	PartnerServers []PartnerServers `hcl:"partner_servers,block" validate:"min=1"`
	// ReadWriteEndpointFailoverPolicy: required
	ReadWriteEndpointFailoverPolicy *ReadWriteEndpointFailoverPolicy `hcl:"read_write_endpoint_failover_policy,block" validate:"required"`
	// ReadonlyEndpointFailoverPolicy: optional
	ReadonlyEndpointFailoverPolicy *ReadonlyEndpointFailoverPolicy `hcl:"readonly_endpoint_failover_policy,block"`
	// Timeouts: optional
	Timeouts *Timeouts `hcl:"timeouts,block"`
}

type azurermSqlFailoverGroupAttributes struct {
	ref terra.Reference
}

// Databases returns a reference to field databases of azurerm_sql_failover_group.
func (asfg azurermSqlFailoverGroupAttributes) Databases() terra.SetValue[terra.StringValue] {
	return terra.ReferenceAsSet[terra.StringValue](asfg.ref.Append("databases"))
}

// Id returns a reference to field id of azurerm_sql_failover_group.
func (asfg azurermSqlFailoverGroupAttributes) Id() terra.StringValue {
	return terra.ReferenceAsString(asfg.ref.Append("id"))
}

// Location returns a reference to field location of azurerm_sql_failover_group.
func (asfg azurermSqlFailoverGroupAttributes) Location() terra.StringValue {
	return terra.ReferenceAsString(asfg.ref.Append("location"))
}

// Name returns a reference to field name of azurerm_sql_failover_group.
func (asfg azurermSqlFailoverGroupAttributes) Name() terra.StringValue {
	return terra.ReferenceAsString(asfg.ref.Append("name"))
}

// ResourceGroupName returns a reference to field resource_group_name of azurerm_sql_failover_group.
func (asfg azurermSqlFailoverGroupAttributes) ResourceGroupName() terra.StringValue {
	return terra.ReferenceAsString(asfg.ref.Append("resource_group_name"))
}

// Role returns a reference to field role of azurerm_sql_failover_group.
func (asfg azurermSqlFailoverGroupAttributes) Role() terra.StringValue {
	return terra.ReferenceAsString(asfg.ref.Append("role"))
}

// ServerName returns a reference to field server_name of azurerm_sql_failover_group.
func (asfg azurermSqlFailoverGroupAttributes) ServerName() terra.StringValue {
	return terra.ReferenceAsString(asfg.ref.Append("server_name"))
}

// Tags returns a reference to field tags of azurerm_sql_failover_group.
func (asfg azurermSqlFailoverGroupAttributes) Tags() terra.MapValue[terra.StringValue] {
	return terra.ReferenceAsMap[terra.StringValue](asfg.ref.Append("tags"))
}

func (asfg azurermSqlFailoverGroupAttributes) PartnerServers() terra.ListValue[PartnerServersAttributes] {
	return terra.ReferenceAsList[PartnerServersAttributes](asfg.ref.Append("partner_servers"))
}

func (asfg azurermSqlFailoverGroupAttributes) ReadWriteEndpointFailoverPolicy() terra.ListValue[ReadWriteEndpointFailoverPolicyAttributes] {
	return terra.ReferenceAsList[ReadWriteEndpointFailoverPolicyAttributes](asfg.ref.Append("read_write_endpoint_failover_policy"))
}

func (asfg azurermSqlFailoverGroupAttributes) ReadonlyEndpointFailoverPolicy() terra.ListValue[ReadonlyEndpointFailoverPolicyAttributes] {
	return terra.ReferenceAsList[ReadonlyEndpointFailoverPolicyAttributes](asfg.ref.Append("readonly_endpoint_failover_policy"))
}

func (asfg azurermSqlFailoverGroupAttributes) Timeouts() TimeoutsAttributes {
	return terra.ReferenceAsSingle[TimeoutsAttributes](asfg.ref.Append("timeouts"))
}

type azurermSqlFailoverGroupState struct {
	Databases                       []string                               `json:"databases"`
	Id                              string                                 `json:"id"`
	Location                        string                                 `json:"location"`
	Name                            string                                 `json:"name"`
	ResourceGroupName               string                                 `json:"resource_group_name"`
	Role                            string                                 `json:"role"`
	ServerName                      string                                 `json:"server_name"`
	Tags                            map[string]string                      `json:"tags"`
	PartnerServers                  []PartnerServersState                  `json:"partner_servers"`
	ReadWriteEndpointFailoverPolicy []ReadWriteEndpointFailoverPolicyState `json:"read_write_endpoint_failover_policy"`
	ReadonlyEndpointFailoverPolicy  []ReadonlyEndpointFailoverPolicyState  `json:"readonly_endpoint_failover_policy"`
	Timeouts                        *TimeoutsState                         `json:"timeouts"`
}
