// CODE GENERATED BY github.com/volvo-cars/lingon. DO NOT EDIT.

package google

import (
	"encoding/json"
	"fmt"
	notebooksinstanceiambinding "github.com/golingon/terraproviders/google/4.59.0/notebooksinstanceiambinding"
	"github.com/volvo-cars/lingon/pkg/terra"
	"io"
)

func NewNotebooksInstanceIamBinding(name string, args NotebooksInstanceIamBindingArgs) *NotebooksInstanceIamBinding {
	return &NotebooksInstanceIamBinding{
		Args: args,
		Name: name,
	}
}

var _ terra.Resource = (*NotebooksInstanceIamBinding)(nil)

type NotebooksInstanceIamBinding struct {
	Name  string
	Args  NotebooksInstanceIamBindingArgs
	state *notebooksInstanceIamBindingState
}

func (niib *NotebooksInstanceIamBinding) Type() string {
	return "google_notebooks_instance_iam_binding"
}

func (niib *NotebooksInstanceIamBinding) LocalName() string {
	return niib.Name
}

func (niib *NotebooksInstanceIamBinding) Configuration() interface{} {
	return niib.Args
}

func (niib *NotebooksInstanceIamBinding) Attributes() notebooksInstanceIamBindingAttributes {
	return notebooksInstanceIamBindingAttributes{ref: terra.ReferenceResource(niib)}
}

func (niib *NotebooksInstanceIamBinding) ImportState(av io.Reader) error {
	niib.state = &notebooksInstanceIamBindingState{}
	if err := json.NewDecoder(av).Decode(niib.state); err != nil {
		return fmt.Errorf("decoding state into resource %s.%s: %w", niib.Type(), niib.LocalName(), err)
	}
	return nil
}

func (niib *NotebooksInstanceIamBinding) State() (*notebooksInstanceIamBindingState, bool) {
	return niib.state, niib.state != nil
}

func (niib *NotebooksInstanceIamBinding) StateMust() *notebooksInstanceIamBindingState {
	if niib.state == nil {
		panic(fmt.Sprintf("state is nil for resource %s.%s", niib.Type(), niib.LocalName()))
	}
	return niib.state
}

func (niib *NotebooksInstanceIamBinding) DependOn() terra.Reference {
	return terra.ReferenceResource(niib)
}

type NotebooksInstanceIamBindingArgs struct {
	// Id: string, optional
	Id terra.StringValue `hcl:"id,attr"`
	// InstanceName: string, required
	InstanceName terra.StringValue `hcl:"instance_name,attr" validate:"required"`
	// Location: string, optional
	Location terra.StringValue `hcl:"location,attr"`
	// Members: set of string, required
	Members terra.SetValue[terra.StringValue] `hcl:"members,attr" validate:"required"`
	// Project: string, optional
	Project terra.StringValue `hcl:"project,attr"`
	// Role: string, required
	Role terra.StringValue `hcl:"role,attr" validate:"required"`
	// Condition: optional
	Condition *notebooksinstanceiambinding.Condition `hcl:"condition,block"`
	// DependsOn contains resources that NotebooksInstanceIamBinding depends on
	DependsOn terra.Dependencies `hcl:"depends_on,attr"`
}
type notebooksInstanceIamBindingAttributes struct {
	ref terra.Reference
}

func (niib notebooksInstanceIamBindingAttributes) Etag() terra.StringValue {
	return terra.ReferenceString(niib.ref.Append("etag"))
}

func (niib notebooksInstanceIamBindingAttributes) Id() terra.StringValue {
	return terra.ReferenceString(niib.ref.Append("id"))
}

func (niib notebooksInstanceIamBindingAttributes) InstanceName() terra.StringValue {
	return terra.ReferenceString(niib.ref.Append("instance_name"))
}

func (niib notebooksInstanceIamBindingAttributes) Location() terra.StringValue {
	return terra.ReferenceString(niib.ref.Append("location"))
}

func (niib notebooksInstanceIamBindingAttributes) Members() terra.SetValue[terra.StringValue] {
	return terra.ReferenceSet[terra.StringValue](niib.ref.Append("members"))
}

func (niib notebooksInstanceIamBindingAttributes) Project() terra.StringValue {
	return terra.ReferenceString(niib.ref.Append("project"))
}

func (niib notebooksInstanceIamBindingAttributes) Role() terra.StringValue {
	return terra.ReferenceString(niib.ref.Append("role"))
}

func (niib notebooksInstanceIamBindingAttributes) Condition() terra.ListValue[notebooksinstanceiambinding.ConditionAttributes] {
	return terra.ReferenceList[notebooksinstanceiambinding.ConditionAttributes](niib.ref.Append("condition"))
}

type notebooksInstanceIamBindingState struct {
	Etag         string                                       `json:"etag"`
	Id           string                                       `json:"id"`
	InstanceName string                                       `json:"instance_name"`
	Location     string                                       `json:"location"`
	Members      []string                                     `json:"members"`
	Project      string                                       `json:"project"`
	Role         string                                       `json:"role"`
	Condition    []notebooksinstanceiambinding.ConditionState `json:"condition"`
}
