// CODE GENERATED BY github.com/golingon/lingon. DO NOT EDIT.

package azurerm_linux_function_app

import "github.com/golingon/lingon/pkg/terra"

// Data creates a new instance of [DataSource].
func Data(name string, args DataArgs) *DataSource {
	return &DataSource{
		Args: args,
		Name: name,
	}
}

var _ terra.DataSource = (*DataSource)(nil)

// DataSource represents the Terraform data resource azurerm_linux_function_app.
type DataSource struct {
	Name string
	Args DataArgs
}

// DataSource returns the Terraform object type for [DataSource].
func (alfa *DataSource) DataSource() string {
	return "azurerm_linux_function_app"
}

// LocalName returns the local name for [DataSource].
func (alfa *DataSource) LocalName() string {
	return alfa.Name
}

// Configuration returns the configuration (args) for [DataSource].
func (alfa *DataSource) Configuration() interface{} {
	return alfa.Args
}

// Attributes returns the attributes for [DataSource].
func (alfa *DataSource) Attributes() dataAzurermLinuxFunctionAppAttributes {
	return dataAzurermLinuxFunctionAppAttributes{ref: terra.ReferenceDataSource(alfa)}
}

// DataArgs contains the configurations for azurerm_linux_function_app.
type DataArgs struct {
	// Id: string, optional
	Id terra.StringValue `hcl:"id,attr"`
	// Name: string, required
	Name terra.StringValue `hcl:"name,attr" validate:"required"`
	// ResourceGroupName: string, required
	ResourceGroupName terra.StringValue `hcl:"resource_group_name,attr" validate:"required"`
	// Timeouts: optional
	Timeouts *DataTimeouts `hcl:"timeouts,block"`
}

type dataAzurermLinuxFunctionAppAttributes struct {
	ref terra.Reference
}

// AppSettings returns a reference to field app_settings of azurerm_linux_function_app.
func (alfa dataAzurermLinuxFunctionAppAttributes) AppSettings() terra.MapValue[terra.StringValue] {
	return terra.ReferenceAsMap[terra.StringValue](alfa.ref.Append("app_settings"))
}

// Availability returns a reference to field availability of azurerm_linux_function_app.
func (alfa dataAzurermLinuxFunctionAppAttributes) Availability() terra.StringValue {
	return terra.ReferenceAsString(alfa.ref.Append("availability"))
}

// BuiltinLoggingEnabled returns a reference to field builtin_logging_enabled of azurerm_linux_function_app.
func (alfa dataAzurermLinuxFunctionAppAttributes) BuiltinLoggingEnabled() terra.BoolValue {
	return terra.ReferenceAsBool(alfa.ref.Append("builtin_logging_enabled"))
}

// ClientCertificateEnabled returns a reference to field client_certificate_enabled of azurerm_linux_function_app.
func (alfa dataAzurermLinuxFunctionAppAttributes) ClientCertificateEnabled() terra.BoolValue {
	return terra.ReferenceAsBool(alfa.ref.Append("client_certificate_enabled"))
}

// ClientCertificateExclusionPaths returns a reference to field client_certificate_exclusion_paths of azurerm_linux_function_app.
func (alfa dataAzurermLinuxFunctionAppAttributes) ClientCertificateExclusionPaths() terra.StringValue {
	return terra.ReferenceAsString(alfa.ref.Append("client_certificate_exclusion_paths"))
}

// ClientCertificateMode returns a reference to field client_certificate_mode of azurerm_linux_function_app.
func (alfa dataAzurermLinuxFunctionAppAttributes) ClientCertificateMode() terra.StringValue {
	return terra.ReferenceAsString(alfa.ref.Append("client_certificate_mode"))
}

// ContentShareForceDisabled returns a reference to field content_share_force_disabled of azurerm_linux_function_app.
func (alfa dataAzurermLinuxFunctionAppAttributes) ContentShareForceDisabled() terra.BoolValue {
	return terra.ReferenceAsBool(alfa.ref.Append("content_share_force_disabled"))
}

// CustomDomainVerificationId returns a reference to field custom_domain_verification_id of azurerm_linux_function_app.
func (alfa dataAzurermLinuxFunctionAppAttributes) CustomDomainVerificationId() terra.StringValue {
	return terra.ReferenceAsString(alfa.ref.Append("custom_domain_verification_id"))
}

// DailyMemoryTimeQuota returns a reference to field daily_memory_time_quota of azurerm_linux_function_app.
func (alfa dataAzurermLinuxFunctionAppAttributes) DailyMemoryTimeQuota() terra.NumberValue {
	return terra.ReferenceAsNumber(alfa.ref.Append("daily_memory_time_quota"))
}

// DefaultHostname returns a reference to field default_hostname of azurerm_linux_function_app.
func (alfa dataAzurermLinuxFunctionAppAttributes) DefaultHostname() terra.StringValue {
	return terra.ReferenceAsString(alfa.ref.Append("default_hostname"))
}

// Enabled returns a reference to field enabled of azurerm_linux_function_app.
func (alfa dataAzurermLinuxFunctionAppAttributes) Enabled() terra.BoolValue {
	return terra.ReferenceAsBool(alfa.ref.Append("enabled"))
}

// FtpPublishBasicAuthenticationEnabled returns a reference to field ftp_publish_basic_authentication_enabled of azurerm_linux_function_app.
func (alfa dataAzurermLinuxFunctionAppAttributes) FtpPublishBasicAuthenticationEnabled() terra.BoolValue {
	return terra.ReferenceAsBool(alfa.ref.Append("ftp_publish_basic_authentication_enabled"))
}

// FunctionsExtensionVersion returns a reference to field functions_extension_version of azurerm_linux_function_app.
func (alfa dataAzurermLinuxFunctionAppAttributes) FunctionsExtensionVersion() terra.StringValue {
	return terra.ReferenceAsString(alfa.ref.Append("functions_extension_version"))
}

// HostingEnvironmentId returns a reference to field hosting_environment_id of azurerm_linux_function_app.
func (alfa dataAzurermLinuxFunctionAppAttributes) HostingEnvironmentId() terra.StringValue {
	return terra.ReferenceAsString(alfa.ref.Append("hosting_environment_id"))
}

// HttpsOnly returns a reference to field https_only of azurerm_linux_function_app.
func (alfa dataAzurermLinuxFunctionAppAttributes) HttpsOnly() terra.BoolValue {
	return terra.ReferenceAsBool(alfa.ref.Append("https_only"))
}

// Id returns a reference to field id of azurerm_linux_function_app.
func (alfa dataAzurermLinuxFunctionAppAttributes) Id() terra.StringValue {
	return terra.ReferenceAsString(alfa.ref.Append("id"))
}

// Kind returns a reference to field kind of azurerm_linux_function_app.
func (alfa dataAzurermLinuxFunctionAppAttributes) Kind() terra.StringValue {
	return terra.ReferenceAsString(alfa.ref.Append("kind"))
}

// Location returns a reference to field location of azurerm_linux_function_app.
func (alfa dataAzurermLinuxFunctionAppAttributes) Location() terra.StringValue {
	return terra.ReferenceAsString(alfa.ref.Append("location"))
}

// Name returns a reference to field name of azurerm_linux_function_app.
func (alfa dataAzurermLinuxFunctionAppAttributes) Name() terra.StringValue {
	return terra.ReferenceAsString(alfa.ref.Append("name"))
}

// OutboundIpAddressList returns a reference to field outbound_ip_address_list of azurerm_linux_function_app.
func (alfa dataAzurermLinuxFunctionAppAttributes) OutboundIpAddressList() terra.ListValue[terra.StringValue] {
	return terra.ReferenceAsList[terra.StringValue](alfa.ref.Append("outbound_ip_address_list"))
}

// OutboundIpAddresses returns a reference to field outbound_ip_addresses of azurerm_linux_function_app.
func (alfa dataAzurermLinuxFunctionAppAttributes) OutboundIpAddresses() terra.StringValue {
	return terra.ReferenceAsString(alfa.ref.Append("outbound_ip_addresses"))
}

// PossibleOutboundIpAddressList returns a reference to field possible_outbound_ip_address_list of azurerm_linux_function_app.
func (alfa dataAzurermLinuxFunctionAppAttributes) PossibleOutboundIpAddressList() terra.ListValue[terra.StringValue] {
	return terra.ReferenceAsList[terra.StringValue](alfa.ref.Append("possible_outbound_ip_address_list"))
}

// PossibleOutboundIpAddresses returns a reference to field possible_outbound_ip_addresses of azurerm_linux_function_app.
func (alfa dataAzurermLinuxFunctionAppAttributes) PossibleOutboundIpAddresses() terra.StringValue {
	return terra.ReferenceAsString(alfa.ref.Append("possible_outbound_ip_addresses"))
}

// PublicNetworkAccessEnabled returns a reference to field public_network_access_enabled of azurerm_linux_function_app.
func (alfa dataAzurermLinuxFunctionAppAttributes) PublicNetworkAccessEnabled() terra.BoolValue {
	return terra.ReferenceAsBool(alfa.ref.Append("public_network_access_enabled"))
}

// ResourceGroupName returns a reference to field resource_group_name of azurerm_linux_function_app.
func (alfa dataAzurermLinuxFunctionAppAttributes) ResourceGroupName() terra.StringValue {
	return terra.ReferenceAsString(alfa.ref.Append("resource_group_name"))
}

// ServicePlanId returns a reference to field service_plan_id of azurerm_linux_function_app.
func (alfa dataAzurermLinuxFunctionAppAttributes) ServicePlanId() terra.StringValue {
	return terra.ReferenceAsString(alfa.ref.Append("service_plan_id"))
}

// StorageAccountAccessKey returns a reference to field storage_account_access_key of azurerm_linux_function_app.
func (alfa dataAzurermLinuxFunctionAppAttributes) StorageAccountAccessKey() terra.StringValue {
	return terra.ReferenceAsString(alfa.ref.Append("storage_account_access_key"))
}

// StorageAccountName returns a reference to field storage_account_name of azurerm_linux_function_app.
func (alfa dataAzurermLinuxFunctionAppAttributes) StorageAccountName() terra.StringValue {
	return terra.ReferenceAsString(alfa.ref.Append("storage_account_name"))
}

// StorageKeyVaultSecretId returns a reference to field storage_key_vault_secret_id of azurerm_linux_function_app.
func (alfa dataAzurermLinuxFunctionAppAttributes) StorageKeyVaultSecretId() terra.StringValue {
	return terra.ReferenceAsString(alfa.ref.Append("storage_key_vault_secret_id"))
}

// StorageUsesManagedIdentity returns a reference to field storage_uses_managed_identity of azurerm_linux_function_app.
func (alfa dataAzurermLinuxFunctionAppAttributes) StorageUsesManagedIdentity() terra.BoolValue {
	return terra.ReferenceAsBool(alfa.ref.Append("storage_uses_managed_identity"))
}

// Tags returns a reference to field tags of azurerm_linux_function_app.
func (alfa dataAzurermLinuxFunctionAppAttributes) Tags() terra.MapValue[terra.StringValue] {
	return terra.ReferenceAsMap[terra.StringValue](alfa.ref.Append("tags"))
}

// Usage returns a reference to field usage of azurerm_linux_function_app.
func (alfa dataAzurermLinuxFunctionAppAttributes) Usage() terra.StringValue {
	return terra.ReferenceAsString(alfa.ref.Append("usage"))
}

// VirtualNetworkSubnetId returns a reference to field virtual_network_subnet_id of azurerm_linux_function_app.
func (alfa dataAzurermLinuxFunctionAppAttributes) VirtualNetworkSubnetId() terra.StringValue {
	return terra.ReferenceAsString(alfa.ref.Append("virtual_network_subnet_id"))
}

// WebdeployPublishBasicAuthenticationEnabled returns a reference to field webdeploy_publish_basic_authentication_enabled of azurerm_linux_function_app.
func (alfa dataAzurermLinuxFunctionAppAttributes) WebdeployPublishBasicAuthenticationEnabled() terra.BoolValue {
	return terra.ReferenceAsBool(alfa.ref.Append("webdeploy_publish_basic_authentication_enabled"))
}

func (alfa dataAzurermLinuxFunctionAppAttributes) AuthSettings() terra.ListValue[DataAuthSettingsAttributes] {
	return terra.ReferenceAsList[DataAuthSettingsAttributes](alfa.ref.Append("auth_settings"))
}

func (alfa dataAzurermLinuxFunctionAppAttributes) AuthSettingsV2() terra.ListValue[DataAuthSettingsV2Attributes] {
	return terra.ReferenceAsList[DataAuthSettingsV2Attributes](alfa.ref.Append("auth_settings_v2"))
}

func (alfa dataAzurermLinuxFunctionAppAttributes) Backup() terra.ListValue[DataBackupAttributes] {
	return terra.ReferenceAsList[DataBackupAttributes](alfa.ref.Append("backup"))
}

func (alfa dataAzurermLinuxFunctionAppAttributes) ConnectionString() terra.SetValue[DataConnectionStringAttributes] {
	return terra.ReferenceAsSet[DataConnectionStringAttributes](alfa.ref.Append("connection_string"))
}

func (alfa dataAzurermLinuxFunctionAppAttributes) Identity() terra.ListValue[DataIdentityAttributes] {
	return terra.ReferenceAsList[DataIdentityAttributes](alfa.ref.Append("identity"))
}

func (alfa dataAzurermLinuxFunctionAppAttributes) SiteConfig() terra.ListValue[DataSiteConfigAttributes] {
	return terra.ReferenceAsList[DataSiteConfigAttributes](alfa.ref.Append("site_config"))
}

func (alfa dataAzurermLinuxFunctionAppAttributes) SiteCredential() terra.ListValue[DataSiteCredentialAttributes] {
	return terra.ReferenceAsList[DataSiteCredentialAttributes](alfa.ref.Append("site_credential"))
}

func (alfa dataAzurermLinuxFunctionAppAttributes) StickySettings() terra.ListValue[DataStickySettingsAttributes] {
	return terra.ReferenceAsList[DataStickySettingsAttributes](alfa.ref.Append("sticky_settings"))
}

func (alfa dataAzurermLinuxFunctionAppAttributes) Timeouts() DataTimeoutsAttributes {
	return terra.ReferenceAsSingle[DataTimeoutsAttributes](alfa.ref.Append("timeouts"))
}
