// CODE GENERATED BY github.com/volvo-cars/lingon. DO NOT EDIT.

package azurerm

import (
	"encoding/json"
	"fmt"
	image "github.com/golingon/terraproviders/azurerm/3.49.0/image"
	"github.com/volvo-cars/lingon/pkg/terra"
	"io"
)

func NewImage(name string, args ImageArgs) *Image {
	return &Image{
		Args: args,
		Name: name,
	}
}

var _ terra.Resource = (*Image)(nil)

type Image struct {
	Name  string
	Args  ImageArgs
	state *imageState
}

func (i *Image) Type() string {
	return "azurerm_image"
}

func (i *Image) LocalName() string {
	return i.Name
}

func (i *Image) Configuration() interface{} {
	return i.Args
}

func (i *Image) Attributes() imageAttributes {
	return imageAttributes{ref: terra.ReferenceResource(i)}
}

func (i *Image) ImportState(av io.Reader) error {
	i.state = &imageState{}
	if err := json.NewDecoder(av).Decode(i.state); err != nil {
		return fmt.Errorf("decoding state into resource %s.%s: %w", i.Type(), i.LocalName(), err)
	}
	return nil
}

func (i *Image) State() (*imageState, bool) {
	return i.state, i.state != nil
}

func (i *Image) StateMust() *imageState {
	if i.state == nil {
		panic(fmt.Sprintf("state is nil for resource %s.%s", i.Type(), i.LocalName()))
	}
	return i.state
}

func (i *Image) DependOn() terra.Reference {
	return terra.ReferenceResource(i)
}

type ImageArgs struct {
	// HyperVGeneration: string, optional
	HyperVGeneration terra.StringValue `hcl:"hyper_v_generation,attr"`
	// Id: string, optional
	Id terra.StringValue `hcl:"id,attr"`
	// Location: string, required
	Location terra.StringValue `hcl:"location,attr" validate:"required"`
	// Name: string, required
	Name terra.StringValue `hcl:"name,attr" validate:"required"`
	// ResourceGroupName: string, required
	ResourceGroupName terra.StringValue `hcl:"resource_group_name,attr" validate:"required"`
	// SourceVirtualMachineId: string, optional
	SourceVirtualMachineId terra.StringValue `hcl:"source_virtual_machine_id,attr"`
	// Tags: map of string, optional
	Tags terra.MapValue[terra.StringValue] `hcl:"tags,attr"`
	// ZoneResilient: bool, optional
	ZoneResilient terra.BoolValue `hcl:"zone_resilient,attr"`
	// DataDisk: min=0
	DataDisk []image.DataDisk `hcl:"data_disk,block" validate:"min=0"`
	// OsDisk: optional
	OsDisk *image.OsDisk `hcl:"os_disk,block"`
	// Timeouts: optional
	Timeouts *image.Timeouts `hcl:"timeouts,block"`
	// DependsOn contains resources that Image depends on
	DependsOn terra.Dependencies `hcl:"depends_on,attr"`
}
type imageAttributes struct {
	ref terra.Reference
}

func (i imageAttributes) HyperVGeneration() terra.StringValue {
	return terra.ReferenceString(i.ref.Append("hyper_v_generation"))
}

func (i imageAttributes) Id() terra.StringValue {
	return terra.ReferenceString(i.ref.Append("id"))
}

func (i imageAttributes) Location() terra.StringValue {
	return terra.ReferenceString(i.ref.Append("location"))
}

func (i imageAttributes) Name() terra.StringValue {
	return terra.ReferenceString(i.ref.Append("name"))
}

func (i imageAttributes) ResourceGroupName() terra.StringValue {
	return terra.ReferenceString(i.ref.Append("resource_group_name"))
}

func (i imageAttributes) SourceVirtualMachineId() terra.StringValue {
	return terra.ReferenceString(i.ref.Append("source_virtual_machine_id"))
}

func (i imageAttributes) Tags() terra.MapValue[terra.StringValue] {
	return terra.ReferenceMap[terra.StringValue](i.ref.Append("tags"))
}

func (i imageAttributes) ZoneResilient() terra.BoolValue {
	return terra.ReferenceBool(i.ref.Append("zone_resilient"))
}

func (i imageAttributes) DataDisk() terra.ListValue[image.DataDiskAttributes] {
	return terra.ReferenceList[image.DataDiskAttributes](i.ref.Append("data_disk"))
}

func (i imageAttributes) OsDisk() terra.ListValue[image.OsDiskAttributes] {
	return terra.ReferenceList[image.OsDiskAttributes](i.ref.Append("os_disk"))
}

func (i imageAttributes) Timeouts() image.TimeoutsAttributes {
	return terra.ReferenceSingle[image.TimeoutsAttributes](i.ref.Append("timeouts"))
}

type imageState struct {
	HyperVGeneration       string                `json:"hyper_v_generation"`
	Id                     string                `json:"id"`
	Location               string                `json:"location"`
	Name                   string                `json:"name"`
	ResourceGroupName      string                `json:"resource_group_name"`
	SourceVirtualMachineId string                `json:"source_virtual_machine_id"`
	Tags                   map[string]string     `json:"tags"`
	ZoneResilient          bool                  `json:"zone_resilient"`
	DataDisk               []image.DataDiskState `json:"data_disk"`
	OsDisk                 []image.OsDiskState   `json:"os_disk"`
	Timeouts               *image.TimeoutsState  `json:"timeouts"`
}
