// CODE GENERATED BY github.com/volvo-cars/lingon. DO NOT EDIT.

package azurerm

import (
	"encoding/json"
	"fmt"
	kustodatabase "github.com/golingon/terraproviders/azurerm/3.49.0/kustodatabase"
	"github.com/volvo-cars/lingon/pkg/terra"
	"io"
)

func NewKustoDatabase(name string, args KustoDatabaseArgs) *KustoDatabase {
	return &KustoDatabase{
		Args: args,
		Name: name,
	}
}

var _ terra.Resource = (*KustoDatabase)(nil)

type KustoDatabase struct {
	Name  string
	Args  KustoDatabaseArgs
	state *kustoDatabaseState
}

func (kd *KustoDatabase) Type() string {
	return "azurerm_kusto_database"
}

func (kd *KustoDatabase) LocalName() string {
	return kd.Name
}

func (kd *KustoDatabase) Configuration() interface{} {
	return kd.Args
}

func (kd *KustoDatabase) Attributes() kustoDatabaseAttributes {
	return kustoDatabaseAttributes{ref: terra.ReferenceResource(kd)}
}

func (kd *KustoDatabase) ImportState(av io.Reader) error {
	kd.state = &kustoDatabaseState{}
	if err := json.NewDecoder(av).Decode(kd.state); err != nil {
		return fmt.Errorf("decoding state into resource %s.%s: %w", kd.Type(), kd.LocalName(), err)
	}
	return nil
}

func (kd *KustoDatabase) State() (*kustoDatabaseState, bool) {
	return kd.state, kd.state != nil
}

func (kd *KustoDatabase) StateMust() *kustoDatabaseState {
	if kd.state == nil {
		panic(fmt.Sprintf("state is nil for resource %s.%s", kd.Type(), kd.LocalName()))
	}
	return kd.state
}

func (kd *KustoDatabase) DependOn() terra.Reference {
	return terra.ReferenceResource(kd)
}

type KustoDatabaseArgs struct {
	// ClusterName: string, required
	ClusterName terra.StringValue `hcl:"cluster_name,attr" validate:"required"`
	// HotCachePeriod: string, optional
	HotCachePeriod terra.StringValue `hcl:"hot_cache_period,attr"`
	// Id: string, optional
	Id terra.StringValue `hcl:"id,attr"`
	// Location: string, required
	Location terra.StringValue `hcl:"location,attr" validate:"required"`
	// Name: string, required
	Name terra.StringValue `hcl:"name,attr" validate:"required"`
	// ResourceGroupName: string, required
	ResourceGroupName terra.StringValue `hcl:"resource_group_name,attr" validate:"required"`
	// SoftDeletePeriod: string, optional
	SoftDeletePeriod terra.StringValue `hcl:"soft_delete_period,attr"`
	// Timeouts: optional
	Timeouts *kustodatabase.Timeouts `hcl:"timeouts,block"`
	// DependsOn contains resources that KustoDatabase depends on
	DependsOn terra.Dependencies `hcl:"depends_on,attr"`
}
type kustoDatabaseAttributes struct {
	ref terra.Reference
}

func (kd kustoDatabaseAttributes) ClusterName() terra.StringValue {
	return terra.ReferenceString(kd.ref.Append("cluster_name"))
}

func (kd kustoDatabaseAttributes) HotCachePeriod() terra.StringValue {
	return terra.ReferenceString(kd.ref.Append("hot_cache_period"))
}

func (kd kustoDatabaseAttributes) Id() terra.StringValue {
	return terra.ReferenceString(kd.ref.Append("id"))
}

func (kd kustoDatabaseAttributes) Location() terra.StringValue {
	return terra.ReferenceString(kd.ref.Append("location"))
}

func (kd kustoDatabaseAttributes) Name() terra.StringValue {
	return terra.ReferenceString(kd.ref.Append("name"))
}

func (kd kustoDatabaseAttributes) ResourceGroupName() terra.StringValue {
	return terra.ReferenceString(kd.ref.Append("resource_group_name"))
}

func (kd kustoDatabaseAttributes) Size() terra.NumberValue {
	return terra.ReferenceNumber(kd.ref.Append("size"))
}

func (kd kustoDatabaseAttributes) SoftDeletePeriod() terra.StringValue {
	return terra.ReferenceString(kd.ref.Append("soft_delete_period"))
}

func (kd kustoDatabaseAttributes) Timeouts() kustodatabase.TimeoutsAttributes {
	return terra.ReferenceSingle[kustodatabase.TimeoutsAttributes](kd.ref.Append("timeouts"))
}

type kustoDatabaseState struct {
	ClusterName       string                       `json:"cluster_name"`
	HotCachePeriod    string                       `json:"hot_cache_period"`
	Id                string                       `json:"id"`
	Location          string                       `json:"location"`
	Name              string                       `json:"name"`
	ResourceGroupName string                       `json:"resource_group_name"`
	Size              float64                      `json:"size"`
	SoftDeletePeriod  string                       `json:"soft_delete_period"`
	Timeouts          *kustodatabase.TimeoutsState `json:"timeouts"`
}
