// CODE GENERATED BY github.com/golingon/lingon. DO NOT EDIT.

package aws

import (
	"github.com/golingon/lingon/pkg/terra"
	datassoadminprincipalapplicationassignments "github.com/golingon/terraproviders/aws/5.44.0/datassoadminprincipalapplicationassignments"
)

// NewDataSsoadminPrincipalApplicationAssignments creates a new instance of [DataSsoadminPrincipalApplicationAssignments].
func NewDataSsoadminPrincipalApplicationAssignments(name string, args DataSsoadminPrincipalApplicationAssignmentsArgs) *DataSsoadminPrincipalApplicationAssignments {
	return &DataSsoadminPrincipalApplicationAssignments{
		Args: args,
		Name: name,
	}
}

var _ terra.DataResource = (*DataSsoadminPrincipalApplicationAssignments)(nil)

// DataSsoadminPrincipalApplicationAssignments represents the Terraform data resource aws_ssoadmin_principal_application_assignments.
type DataSsoadminPrincipalApplicationAssignments struct {
	Name string
	Args DataSsoadminPrincipalApplicationAssignmentsArgs
}

// DataSource returns the Terraform object type for [DataSsoadminPrincipalApplicationAssignments].
func (spaa *DataSsoadminPrincipalApplicationAssignments) DataSource() string {
	return "aws_ssoadmin_principal_application_assignments"
}

// LocalName returns the local name for [DataSsoadminPrincipalApplicationAssignments].
func (spaa *DataSsoadminPrincipalApplicationAssignments) LocalName() string {
	return spaa.Name
}

// Configuration returns the configuration (args) for [DataSsoadminPrincipalApplicationAssignments].
func (spaa *DataSsoadminPrincipalApplicationAssignments) Configuration() interface{} {
	return spaa.Args
}

// Attributes returns the attributes for [DataSsoadminPrincipalApplicationAssignments].
func (spaa *DataSsoadminPrincipalApplicationAssignments) Attributes() dataSsoadminPrincipalApplicationAssignmentsAttributes {
	return dataSsoadminPrincipalApplicationAssignmentsAttributes{ref: terra.ReferenceDataResource(spaa)}
}

// DataSsoadminPrincipalApplicationAssignmentsArgs contains the configurations for aws_ssoadmin_principal_application_assignments.
type DataSsoadminPrincipalApplicationAssignmentsArgs struct {
	// InstanceArn: string, required
	InstanceArn terra.StringValue `hcl:"instance_arn,attr" validate:"required"`
	// PrincipalId: string, required
	PrincipalId terra.StringValue `hcl:"principal_id,attr" validate:"required"`
	// PrincipalType: string, required
	PrincipalType terra.StringValue `hcl:"principal_type,attr" validate:"required"`
	// ApplicationAssignments: min=0
	ApplicationAssignments []datassoadminprincipalapplicationassignments.ApplicationAssignments `hcl:"application_assignments,block" validate:"min=0"`
}
type dataSsoadminPrincipalApplicationAssignmentsAttributes struct {
	ref terra.Reference
}

// Id returns a reference to field id of aws_ssoadmin_principal_application_assignments.
func (spaa dataSsoadminPrincipalApplicationAssignmentsAttributes) Id() terra.StringValue {
	return terra.ReferenceAsString(spaa.ref.Append("id"))
}

// InstanceArn returns a reference to field instance_arn of aws_ssoadmin_principal_application_assignments.
func (spaa dataSsoadminPrincipalApplicationAssignmentsAttributes) InstanceArn() terra.StringValue {
	return terra.ReferenceAsString(spaa.ref.Append("instance_arn"))
}

// PrincipalId returns a reference to field principal_id of aws_ssoadmin_principal_application_assignments.
func (spaa dataSsoadminPrincipalApplicationAssignmentsAttributes) PrincipalId() terra.StringValue {
	return terra.ReferenceAsString(spaa.ref.Append("principal_id"))
}

// PrincipalType returns a reference to field principal_type of aws_ssoadmin_principal_application_assignments.
func (spaa dataSsoadminPrincipalApplicationAssignmentsAttributes) PrincipalType() terra.StringValue {
	return terra.ReferenceAsString(spaa.ref.Append("principal_type"))
}

func (spaa dataSsoadminPrincipalApplicationAssignmentsAttributes) ApplicationAssignments() terra.ListValue[datassoadminprincipalapplicationassignments.ApplicationAssignmentsAttributes] {
	return terra.ReferenceAsList[datassoadminprincipalapplicationassignments.ApplicationAssignmentsAttributes](spaa.ref.Append("application_assignments"))
}
