// CODE GENERATED BY github.com/golingon/lingon. DO NOT EDIT.

package azurerm_api_management_user

import "github.com/golingon/lingon/pkg/terra"

// Data creates a new instance of [DataSource].
func Data(name string, args DataArgs) *DataSource {
	return &DataSource{
		Args: args,
		Name: name,
	}
}

var _ terra.DataSource = (*DataSource)(nil)

// DataSource represents the Terraform data resource azurerm_api_management_user.
type DataSource struct {
	Name string
	Args DataArgs
}

// DataSource returns the Terraform object type for [DataSource].
func (aamu *DataSource) DataSource() string {
	return "azurerm_api_management_user"
}

// LocalName returns the local name for [DataSource].
func (aamu *DataSource) LocalName() string {
	return aamu.Name
}

// Configuration returns the configuration (args) for [DataSource].
func (aamu *DataSource) Configuration() interface{} {
	return aamu.Args
}

// Attributes returns the attributes for [DataSource].
func (aamu *DataSource) Attributes() dataAzurermApiManagementUserAttributes {
	return dataAzurermApiManagementUserAttributes{ref: terra.ReferenceDataSource(aamu)}
}

// DataArgs contains the configurations for azurerm_api_management_user.
type DataArgs struct {
	// ApiManagementName: string, required
	ApiManagementName terra.StringValue `hcl:"api_management_name,attr" validate:"required"`
	// Id: string, optional
	Id terra.StringValue `hcl:"id,attr"`
	// ResourceGroupName: string, required
	ResourceGroupName terra.StringValue `hcl:"resource_group_name,attr" validate:"required"`
	// UserId: string, required
	UserId terra.StringValue `hcl:"user_id,attr" validate:"required"`
	// Timeouts: optional
	Timeouts *DataTimeouts `hcl:"timeouts,block"`
}

type dataAzurermApiManagementUserAttributes struct {
	ref terra.Reference
}

// ApiManagementName returns a reference to field api_management_name of azurerm_api_management_user.
func (aamu dataAzurermApiManagementUserAttributes) ApiManagementName() terra.StringValue {
	return terra.ReferenceAsString(aamu.ref.Append("api_management_name"))
}

// Email returns a reference to field email of azurerm_api_management_user.
func (aamu dataAzurermApiManagementUserAttributes) Email() terra.StringValue {
	return terra.ReferenceAsString(aamu.ref.Append("email"))
}

// FirstName returns a reference to field first_name of azurerm_api_management_user.
func (aamu dataAzurermApiManagementUserAttributes) FirstName() terra.StringValue {
	return terra.ReferenceAsString(aamu.ref.Append("first_name"))
}

// Id returns a reference to field id of azurerm_api_management_user.
func (aamu dataAzurermApiManagementUserAttributes) Id() terra.StringValue {
	return terra.ReferenceAsString(aamu.ref.Append("id"))
}

// LastName returns a reference to field last_name of azurerm_api_management_user.
func (aamu dataAzurermApiManagementUserAttributes) LastName() terra.StringValue {
	return terra.ReferenceAsString(aamu.ref.Append("last_name"))
}

// Note returns a reference to field note of azurerm_api_management_user.
func (aamu dataAzurermApiManagementUserAttributes) Note() terra.StringValue {
	return terra.ReferenceAsString(aamu.ref.Append("note"))
}

// ResourceGroupName returns a reference to field resource_group_name of azurerm_api_management_user.
func (aamu dataAzurermApiManagementUserAttributes) ResourceGroupName() terra.StringValue {
	return terra.ReferenceAsString(aamu.ref.Append("resource_group_name"))
}

// State returns a reference to field state of azurerm_api_management_user.
func (aamu dataAzurermApiManagementUserAttributes) State() terra.StringValue {
	return terra.ReferenceAsString(aamu.ref.Append("state"))
}

// UserId returns a reference to field user_id of azurerm_api_management_user.
func (aamu dataAzurermApiManagementUserAttributes) UserId() terra.StringValue {
	return terra.ReferenceAsString(aamu.ref.Append("user_id"))
}

func (aamu dataAzurermApiManagementUserAttributes) Timeouts() DataTimeoutsAttributes {
	return terra.ReferenceAsSingle[DataTimeoutsAttributes](aamu.ref.Append("timeouts"))
}
