// CODE GENERATED BY github.com/golingon/lingon. DO NOT EDIT.

package azurerm_bot_channel_email

import (
	"encoding/json"
	"fmt"
	"github.com/golingon/lingon/pkg/terra"
	"io"
)

// New creates a new instance of [Resource].
func New(name string, args Args) *Resource {
	return &Resource{
		Args: args,
		Name: name,
	}
}

var _ terra.Resource = (*Resource)(nil)

// Resource represents the Terraform resource azurerm_bot_channel_email.
type Resource struct {
	Name      string
	Args      Args
	state     *azurermBotChannelEmailState
	DependsOn terra.Dependencies
	Lifecycle *terra.Lifecycle
}

// Type returns the Terraform object type for [Resource].
func (abce *Resource) Type() string {
	return "azurerm_bot_channel_email"
}

// LocalName returns the local name for [Resource].
func (abce *Resource) LocalName() string {
	return abce.Name
}

// Configuration returns the configuration (args) for [Resource].
func (abce *Resource) Configuration() interface{} {
	return abce.Args
}

// DependOn is used for other resources to depend on [Resource].
func (abce *Resource) DependOn() terra.Reference {
	return terra.ReferenceResource(abce)
}

// Dependencies returns the list of resources [Resource] depends_on.
func (abce *Resource) Dependencies() terra.Dependencies {
	return abce.DependsOn
}

// LifecycleManagement returns the lifecycle block for [Resource].
func (abce *Resource) LifecycleManagement() *terra.Lifecycle {
	return abce.Lifecycle
}

// Attributes returns the attributes for [Resource].
func (abce *Resource) Attributes() azurermBotChannelEmailAttributes {
	return azurermBotChannelEmailAttributes{ref: terra.ReferenceResource(abce)}
}

// ImportState imports the given attribute values into [Resource]'s state.
func (abce *Resource) ImportState(state io.Reader) error {
	abce.state = &azurermBotChannelEmailState{}
	if err := json.NewDecoder(state).Decode(abce.state); err != nil {
		return fmt.Errorf("decoding state into resource %s.%s: %w", abce.Type(), abce.LocalName(), err)
	}
	return nil
}

// State returns the state and a bool indicating if [Resource] has state.
func (abce *Resource) State() (*azurermBotChannelEmailState, bool) {
	return abce.state, abce.state != nil
}

// StateMust returns the state for [Resource]. Panics if the state is nil.
func (abce *Resource) StateMust() *azurermBotChannelEmailState {
	if abce.state == nil {
		panic(fmt.Sprintf("state is nil for resource %s.%s", abce.Type(), abce.LocalName()))
	}
	return abce.state
}

// Args contains the configurations for azurerm_bot_channel_email.
type Args struct {
	// BotName: string, required
	BotName terra.StringValue `hcl:"bot_name,attr" validate:"required"`
	// EmailAddress: string, required
	EmailAddress terra.StringValue `hcl:"email_address,attr" validate:"required"`
	// EmailPassword: string, optional
	EmailPassword terra.StringValue `hcl:"email_password,attr"`
	// Id: string, optional
	Id terra.StringValue `hcl:"id,attr"`
	// Location: string, required
	Location terra.StringValue `hcl:"location,attr" validate:"required"`
	// MagicCode: string, optional
	MagicCode terra.StringValue `hcl:"magic_code,attr"`
	// ResourceGroupName: string, required
	ResourceGroupName terra.StringValue `hcl:"resource_group_name,attr" validate:"required"`
	// Timeouts: optional
	Timeouts *Timeouts `hcl:"timeouts,block"`
}

type azurermBotChannelEmailAttributes struct {
	ref terra.Reference
}

// BotName returns a reference to field bot_name of azurerm_bot_channel_email.
func (abce azurermBotChannelEmailAttributes) BotName() terra.StringValue {
	return terra.ReferenceAsString(abce.ref.Append("bot_name"))
}

// EmailAddress returns a reference to field email_address of azurerm_bot_channel_email.
func (abce azurermBotChannelEmailAttributes) EmailAddress() terra.StringValue {
	return terra.ReferenceAsString(abce.ref.Append("email_address"))
}

// EmailPassword returns a reference to field email_password of azurerm_bot_channel_email.
func (abce azurermBotChannelEmailAttributes) EmailPassword() terra.StringValue {
	return terra.ReferenceAsString(abce.ref.Append("email_password"))
}

// Id returns a reference to field id of azurerm_bot_channel_email.
func (abce azurermBotChannelEmailAttributes) Id() terra.StringValue {
	return terra.ReferenceAsString(abce.ref.Append("id"))
}

// Location returns a reference to field location of azurerm_bot_channel_email.
func (abce azurermBotChannelEmailAttributes) Location() terra.StringValue {
	return terra.ReferenceAsString(abce.ref.Append("location"))
}

// MagicCode returns a reference to field magic_code of azurerm_bot_channel_email.
func (abce azurermBotChannelEmailAttributes) MagicCode() terra.StringValue {
	return terra.ReferenceAsString(abce.ref.Append("magic_code"))
}

// ResourceGroupName returns a reference to field resource_group_name of azurerm_bot_channel_email.
func (abce azurermBotChannelEmailAttributes) ResourceGroupName() terra.StringValue {
	return terra.ReferenceAsString(abce.ref.Append("resource_group_name"))
}

func (abce azurermBotChannelEmailAttributes) Timeouts() TimeoutsAttributes {
	return terra.ReferenceAsSingle[TimeoutsAttributes](abce.ref.Append("timeouts"))
}

type azurermBotChannelEmailState struct {
	BotName           string         `json:"bot_name"`
	EmailAddress      string         `json:"email_address"`
	EmailPassword     string         `json:"email_password"`
	Id                string         `json:"id"`
	Location          string         `json:"location"`
	MagicCode         string         `json:"magic_code"`
	ResourceGroupName string         `json:"resource_group_name"`
	Timeouts          *TimeoutsState `json:"timeouts"`
}
