// CODE GENERATED BY github.com/golingon/lingon. DO NOT EDIT.

package azuread_access_package

import "github.com/golingon/lingon/pkg/terra"

// Data creates a new instance of [DataSource].
func Data(name string, args DataArgs) *DataSource {
	return &DataSource{
		Args: args,
		Name: name,
	}
}

var _ terra.DataSource = (*DataSource)(nil)

// DataSource represents the Terraform data resource azuread_access_package.
type DataSource struct {
	Name string
	Args DataArgs
}

// DataSource returns the Terraform object type for [DataSource].
func (aap *DataSource) DataSource() string {
	return "azuread_access_package"
}

// LocalName returns the local name for [DataSource].
func (aap *DataSource) LocalName() string {
	return aap.Name
}

// Configuration returns the configuration (args) for [DataSource].
func (aap *DataSource) Configuration() interface{} {
	return aap.Args
}

// Attributes returns the attributes for [DataSource].
func (aap *DataSource) Attributes() dataAzureadAccessPackageAttributes {
	return dataAzureadAccessPackageAttributes{ref: terra.ReferenceDataSource(aap)}
}

// DataArgs contains the configurations for azuread_access_package.
type DataArgs struct {
	// CatalogId: string, optional
	CatalogId terra.StringValue `hcl:"catalog_id,attr"`
	// DisplayName: string, optional
	DisplayName terra.StringValue `hcl:"display_name,attr"`
	// Id: string, optional
	Id terra.StringValue `hcl:"id,attr"`
	// ObjectId: string, optional
	ObjectId terra.StringValue `hcl:"object_id,attr"`
	// Timeouts: optional
	Timeouts *DataTimeouts `hcl:"timeouts,block"`
}

type dataAzureadAccessPackageAttributes struct {
	ref terra.Reference
}

// CatalogId returns a reference to field catalog_id of azuread_access_package.
func (aap dataAzureadAccessPackageAttributes) CatalogId() terra.StringValue {
	return terra.ReferenceAsString(aap.ref.Append("catalog_id"))
}

// Description returns a reference to field description of azuread_access_package.
func (aap dataAzureadAccessPackageAttributes) Description() terra.StringValue {
	return terra.ReferenceAsString(aap.ref.Append("description"))
}

// DisplayName returns a reference to field display_name of azuread_access_package.
func (aap dataAzureadAccessPackageAttributes) DisplayName() terra.StringValue {
	return terra.ReferenceAsString(aap.ref.Append("display_name"))
}

// Hidden returns a reference to field hidden of azuread_access_package.
func (aap dataAzureadAccessPackageAttributes) Hidden() terra.BoolValue {
	return terra.ReferenceAsBool(aap.ref.Append("hidden"))
}

// Id returns a reference to field id of azuread_access_package.
func (aap dataAzureadAccessPackageAttributes) Id() terra.StringValue {
	return terra.ReferenceAsString(aap.ref.Append("id"))
}

// ObjectId returns a reference to field object_id of azuread_access_package.
func (aap dataAzureadAccessPackageAttributes) ObjectId() terra.StringValue {
	return terra.ReferenceAsString(aap.ref.Append("object_id"))
}

func (aap dataAzureadAccessPackageAttributes) Timeouts() DataTimeoutsAttributes {
	return terra.ReferenceAsSingle[DataTimeoutsAttributes](aap.ref.Append("timeouts"))
}
