// CODE GENERATED BY github.com/golingon/lingon. DO NOT EDIT.

package google_netapp_volume

import (
	terra "github.com/golingon/lingon/pkg/terra"
	hclwrite "github.com/hashicorp/hcl/v2/hclwrite"
)

type ExportPolicy struct {
	// ExportPolicyRules: min=1
	Rules []ExportPolicyRules `hcl:"rules,block" validate:"min=1"`
}

type ExportPolicyRules struct {
	// AccessType: string, optional
	AccessType terra.StringValue `hcl:"access_type,attr"`
	// AllowedClients: string, optional
	AllowedClients terra.StringValue `hcl:"allowed_clients,attr"`
	// HasRootAccess: string, optional
	HasRootAccess terra.StringValue `hcl:"has_root_access,attr"`
	// Kerberos5ReadOnly: bool, optional
	Kerberos5ReadOnly terra.BoolValue `hcl:"kerberos5_read_only,attr"`
	// Kerberos5ReadWrite: bool, optional
	Kerberos5ReadWrite terra.BoolValue `hcl:"kerberos5_read_write,attr"`
	// Kerberos5IReadOnly: bool, optional
	Kerberos5IReadOnly terra.BoolValue `hcl:"kerberos5i_read_only,attr"`
	// Kerberos5IReadWrite: bool, optional
	Kerberos5IReadWrite terra.BoolValue `hcl:"kerberos5i_read_write,attr"`
	// Kerberos5PReadOnly: bool, optional
	Kerberos5PReadOnly terra.BoolValue `hcl:"kerberos5p_read_only,attr"`
	// Kerberos5PReadWrite: bool, optional
	Kerberos5PReadWrite terra.BoolValue `hcl:"kerberos5p_read_write,attr"`
	// Nfsv3: bool, optional
	Nfsv3 terra.BoolValue `hcl:"nfsv3,attr"`
	// Nfsv4: bool, optional
	Nfsv4 terra.BoolValue `hcl:"nfsv4,attr"`
}

type RestoreParameters struct {
	// SourceBackup: string, optional
	SourceBackup terra.StringValue `hcl:"source_backup,attr"`
	// SourceSnapshot: string, optional
	SourceSnapshot terra.StringValue `hcl:"source_snapshot,attr"`
}

type SnapshotPolicy struct {
	// Enabled: bool, optional
	Enabled terra.BoolValue `hcl:"enabled,attr"`
	// SnapshotPolicyDailySchedule: optional
	DailySchedule *SnapshotPolicyDailySchedule `hcl:"daily_schedule,block"`
	// SnapshotPolicyHourlySchedule: optional
	HourlySchedule *SnapshotPolicyHourlySchedule `hcl:"hourly_schedule,block"`
	// SnapshotPolicyMonthlySchedule: optional
	MonthlySchedule *SnapshotPolicyMonthlySchedule `hcl:"monthly_schedule,block"`
	// SnapshotPolicyWeeklySchedule: optional
	WeeklySchedule *SnapshotPolicyWeeklySchedule `hcl:"weekly_schedule,block"`
}

type SnapshotPolicyDailySchedule struct {
	// Hour: number, optional
	Hour terra.NumberValue `hcl:"hour,attr"`
	// Minute: number, optional
	Minute terra.NumberValue `hcl:"minute,attr"`
	// SnapshotsToKeep: number, required
	SnapshotsToKeep terra.NumberValue `hcl:"snapshots_to_keep,attr" validate:"required"`
}

type SnapshotPolicyHourlySchedule struct {
	// Minute: number, optional
	Minute terra.NumberValue `hcl:"minute,attr"`
	// SnapshotsToKeep: number, required
	SnapshotsToKeep terra.NumberValue `hcl:"snapshots_to_keep,attr" validate:"required"`
}

type SnapshotPolicyMonthlySchedule struct {
	// DaysOfMonth: string, optional
	DaysOfMonth terra.StringValue `hcl:"days_of_month,attr"`
	// Hour: number, optional
	Hour terra.NumberValue `hcl:"hour,attr"`
	// Minute: number, optional
	Minute terra.NumberValue `hcl:"minute,attr"`
	// SnapshotsToKeep: number, required
	SnapshotsToKeep terra.NumberValue `hcl:"snapshots_to_keep,attr" validate:"required"`
}

type SnapshotPolicyWeeklySchedule struct {
	// Day: string, optional
	Day terra.StringValue `hcl:"day,attr"`
	// Hour: number, optional
	Hour terra.NumberValue `hcl:"hour,attr"`
	// Minute: number, optional
	Minute terra.NumberValue `hcl:"minute,attr"`
	// SnapshotsToKeep: number, required
	SnapshotsToKeep terra.NumberValue `hcl:"snapshots_to_keep,attr" validate:"required"`
}

type Timeouts struct {
	// Create: string, optional
	Create terra.StringValue `hcl:"create,attr"`
	// Delete: string, optional
	Delete terra.StringValue `hcl:"delete,attr"`
	// Update: string, optional
	Update terra.StringValue `hcl:"update,attr"`
}

type MountOptionsAttributes struct {
	ref terra.Reference
}

func (mo MountOptionsAttributes) InternalRef() (terra.Reference, error) {
	return mo.ref, nil
}

func (mo MountOptionsAttributes) InternalWithRef(ref terra.Reference) MountOptionsAttributes {
	return MountOptionsAttributes{ref: ref}
}

func (mo MountOptionsAttributes) InternalTokens() (hclwrite.Tokens, error) {
	return mo.ref.InternalTokens()
}

func (mo MountOptionsAttributes) Export() terra.StringValue {
	return terra.ReferenceAsString(mo.ref.Append("export"))
}

func (mo MountOptionsAttributes) ExportFull() terra.StringValue {
	return terra.ReferenceAsString(mo.ref.Append("export_full"))
}

func (mo MountOptionsAttributes) Instructions() terra.StringValue {
	return terra.ReferenceAsString(mo.ref.Append("instructions"))
}

func (mo MountOptionsAttributes) Protocol() terra.StringValue {
	return terra.ReferenceAsString(mo.ref.Append("protocol"))
}

type ExportPolicyAttributes struct {
	ref terra.Reference
}

func (ep ExportPolicyAttributes) InternalRef() (terra.Reference, error) {
	return ep.ref, nil
}

func (ep ExportPolicyAttributes) InternalWithRef(ref terra.Reference) ExportPolicyAttributes {
	return ExportPolicyAttributes{ref: ref}
}

func (ep ExportPolicyAttributes) InternalTokens() (hclwrite.Tokens, error) {
	return ep.ref.InternalTokens()
}

func (ep ExportPolicyAttributes) Rules() terra.ListValue[ExportPolicyRulesAttributes] {
	return terra.ReferenceAsList[ExportPolicyRulesAttributes](ep.ref.Append("rules"))
}

type ExportPolicyRulesAttributes struct {
	ref terra.Reference
}

func (r ExportPolicyRulesAttributes) InternalRef() (terra.Reference, error) {
	return r.ref, nil
}

func (r ExportPolicyRulesAttributes) InternalWithRef(ref terra.Reference) ExportPolicyRulesAttributes {
	return ExportPolicyRulesAttributes{ref: ref}
}

func (r ExportPolicyRulesAttributes) InternalTokens() (hclwrite.Tokens, error) {
	return r.ref.InternalTokens()
}

func (r ExportPolicyRulesAttributes) AccessType() terra.StringValue {
	return terra.ReferenceAsString(r.ref.Append("access_type"))
}

func (r ExportPolicyRulesAttributes) AllowedClients() terra.StringValue {
	return terra.ReferenceAsString(r.ref.Append("allowed_clients"))
}

func (r ExportPolicyRulesAttributes) HasRootAccess() terra.StringValue {
	return terra.ReferenceAsString(r.ref.Append("has_root_access"))
}

func (r ExportPolicyRulesAttributes) Kerberos5ReadOnly() terra.BoolValue {
	return terra.ReferenceAsBool(r.ref.Append("kerberos5_read_only"))
}

func (r ExportPolicyRulesAttributes) Kerberos5ReadWrite() terra.BoolValue {
	return terra.ReferenceAsBool(r.ref.Append("kerberos5_read_write"))
}

func (r ExportPolicyRulesAttributes) Kerberos5IReadOnly() terra.BoolValue {
	return terra.ReferenceAsBool(r.ref.Append("kerberos5i_read_only"))
}

func (r ExportPolicyRulesAttributes) Kerberos5IReadWrite() terra.BoolValue {
	return terra.ReferenceAsBool(r.ref.Append("kerberos5i_read_write"))
}

func (r ExportPolicyRulesAttributes) Kerberos5PReadOnly() terra.BoolValue {
	return terra.ReferenceAsBool(r.ref.Append("kerberos5p_read_only"))
}

func (r ExportPolicyRulesAttributes) Kerberos5PReadWrite() terra.BoolValue {
	return terra.ReferenceAsBool(r.ref.Append("kerberos5p_read_write"))
}

func (r ExportPolicyRulesAttributes) Nfsv3() terra.BoolValue {
	return terra.ReferenceAsBool(r.ref.Append("nfsv3"))
}

func (r ExportPolicyRulesAttributes) Nfsv4() terra.BoolValue {
	return terra.ReferenceAsBool(r.ref.Append("nfsv4"))
}

type RestoreParametersAttributes struct {
	ref terra.Reference
}

func (rp RestoreParametersAttributes) InternalRef() (terra.Reference, error) {
	return rp.ref, nil
}

func (rp RestoreParametersAttributes) InternalWithRef(ref terra.Reference) RestoreParametersAttributes {
	return RestoreParametersAttributes{ref: ref}
}

func (rp RestoreParametersAttributes) InternalTokens() (hclwrite.Tokens, error) {
	return rp.ref.InternalTokens()
}

func (rp RestoreParametersAttributes) SourceBackup() terra.StringValue {
	return terra.ReferenceAsString(rp.ref.Append("source_backup"))
}

func (rp RestoreParametersAttributes) SourceSnapshot() terra.StringValue {
	return terra.ReferenceAsString(rp.ref.Append("source_snapshot"))
}

type SnapshotPolicyAttributes struct {
	ref terra.Reference
}

func (sp SnapshotPolicyAttributes) InternalRef() (terra.Reference, error) {
	return sp.ref, nil
}

func (sp SnapshotPolicyAttributes) InternalWithRef(ref terra.Reference) SnapshotPolicyAttributes {
	return SnapshotPolicyAttributes{ref: ref}
}

func (sp SnapshotPolicyAttributes) InternalTokens() (hclwrite.Tokens, error) {
	return sp.ref.InternalTokens()
}

func (sp SnapshotPolicyAttributes) Enabled() terra.BoolValue {
	return terra.ReferenceAsBool(sp.ref.Append("enabled"))
}

func (sp SnapshotPolicyAttributes) DailySchedule() terra.ListValue[SnapshotPolicyDailyScheduleAttributes] {
	return terra.ReferenceAsList[SnapshotPolicyDailyScheduleAttributes](sp.ref.Append("daily_schedule"))
}

func (sp SnapshotPolicyAttributes) HourlySchedule() terra.ListValue[SnapshotPolicyHourlyScheduleAttributes] {
	return terra.ReferenceAsList[SnapshotPolicyHourlyScheduleAttributes](sp.ref.Append("hourly_schedule"))
}

func (sp SnapshotPolicyAttributes) MonthlySchedule() terra.ListValue[SnapshotPolicyMonthlyScheduleAttributes] {
	return terra.ReferenceAsList[SnapshotPolicyMonthlyScheduleAttributes](sp.ref.Append("monthly_schedule"))
}

func (sp SnapshotPolicyAttributes) WeeklySchedule() terra.ListValue[SnapshotPolicyWeeklyScheduleAttributes] {
	return terra.ReferenceAsList[SnapshotPolicyWeeklyScheduleAttributes](sp.ref.Append("weekly_schedule"))
}

type SnapshotPolicyDailyScheduleAttributes struct {
	ref terra.Reference
}

func (ds SnapshotPolicyDailyScheduleAttributes) InternalRef() (terra.Reference, error) {
	return ds.ref, nil
}

func (ds SnapshotPolicyDailyScheduleAttributes) InternalWithRef(ref terra.Reference) SnapshotPolicyDailyScheduleAttributes {
	return SnapshotPolicyDailyScheduleAttributes{ref: ref}
}

func (ds SnapshotPolicyDailyScheduleAttributes) InternalTokens() (hclwrite.Tokens, error) {
	return ds.ref.InternalTokens()
}

func (ds SnapshotPolicyDailyScheduleAttributes) Hour() terra.NumberValue {
	return terra.ReferenceAsNumber(ds.ref.Append("hour"))
}

func (ds SnapshotPolicyDailyScheduleAttributes) Minute() terra.NumberValue {
	return terra.ReferenceAsNumber(ds.ref.Append("minute"))
}

func (ds SnapshotPolicyDailyScheduleAttributes) SnapshotsToKeep() terra.NumberValue {
	return terra.ReferenceAsNumber(ds.ref.Append("snapshots_to_keep"))
}

type SnapshotPolicyHourlyScheduleAttributes struct {
	ref terra.Reference
}

func (hs SnapshotPolicyHourlyScheduleAttributes) InternalRef() (terra.Reference, error) {
	return hs.ref, nil
}

func (hs SnapshotPolicyHourlyScheduleAttributes) InternalWithRef(ref terra.Reference) SnapshotPolicyHourlyScheduleAttributes {
	return SnapshotPolicyHourlyScheduleAttributes{ref: ref}
}

func (hs SnapshotPolicyHourlyScheduleAttributes) InternalTokens() (hclwrite.Tokens, error) {
	return hs.ref.InternalTokens()
}

func (hs SnapshotPolicyHourlyScheduleAttributes) Minute() terra.NumberValue {
	return terra.ReferenceAsNumber(hs.ref.Append("minute"))
}

func (hs SnapshotPolicyHourlyScheduleAttributes) SnapshotsToKeep() terra.NumberValue {
	return terra.ReferenceAsNumber(hs.ref.Append("snapshots_to_keep"))
}

type SnapshotPolicyMonthlyScheduleAttributes struct {
	ref terra.Reference
}

func (ms SnapshotPolicyMonthlyScheduleAttributes) InternalRef() (terra.Reference, error) {
	return ms.ref, nil
}

func (ms SnapshotPolicyMonthlyScheduleAttributes) InternalWithRef(ref terra.Reference) SnapshotPolicyMonthlyScheduleAttributes {
	return SnapshotPolicyMonthlyScheduleAttributes{ref: ref}
}

func (ms SnapshotPolicyMonthlyScheduleAttributes) InternalTokens() (hclwrite.Tokens, error) {
	return ms.ref.InternalTokens()
}

func (ms SnapshotPolicyMonthlyScheduleAttributes) DaysOfMonth() terra.StringValue {
	return terra.ReferenceAsString(ms.ref.Append("days_of_month"))
}

func (ms SnapshotPolicyMonthlyScheduleAttributes) Hour() terra.NumberValue {
	return terra.ReferenceAsNumber(ms.ref.Append("hour"))
}

func (ms SnapshotPolicyMonthlyScheduleAttributes) Minute() terra.NumberValue {
	return terra.ReferenceAsNumber(ms.ref.Append("minute"))
}

func (ms SnapshotPolicyMonthlyScheduleAttributes) SnapshotsToKeep() terra.NumberValue {
	return terra.ReferenceAsNumber(ms.ref.Append("snapshots_to_keep"))
}

type SnapshotPolicyWeeklyScheduleAttributes struct {
	ref terra.Reference
}

func (ws SnapshotPolicyWeeklyScheduleAttributes) InternalRef() (terra.Reference, error) {
	return ws.ref, nil
}

func (ws SnapshotPolicyWeeklyScheduleAttributes) InternalWithRef(ref terra.Reference) SnapshotPolicyWeeklyScheduleAttributes {
	return SnapshotPolicyWeeklyScheduleAttributes{ref: ref}
}

func (ws SnapshotPolicyWeeklyScheduleAttributes) InternalTokens() (hclwrite.Tokens, error) {
	return ws.ref.InternalTokens()
}

func (ws SnapshotPolicyWeeklyScheduleAttributes) Day() terra.StringValue {
	return terra.ReferenceAsString(ws.ref.Append("day"))
}

func (ws SnapshotPolicyWeeklyScheduleAttributes) Hour() terra.NumberValue {
	return terra.ReferenceAsNumber(ws.ref.Append("hour"))
}

func (ws SnapshotPolicyWeeklyScheduleAttributes) Minute() terra.NumberValue {
	return terra.ReferenceAsNumber(ws.ref.Append("minute"))
}

func (ws SnapshotPolicyWeeklyScheduleAttributes) SnapshotsToKeep() terra.NumberValue {
	return terra.ReferenceAsNumber(ws.ref.Append("snapshots_to_keep"))
}

type TimeoutsAttributes struct {
	ref terra.Reference
}

func (t TimeoutsAttributes) InternalRef() (terra.Reference, error) {
	return t.ref, nil
}

func (t TimeoutsAttributes) InternalWithRef(ref terra.Reference) TimeoutsAttributes {
	return TimeoutsAttributes{ref: ref}
}

func (t TimeoutsAttributes) InternalTokens() (hclwrite.Tokens, error) {
	return t.ref.InternalTokens()
}

func (t TimeoutsAttributes) Create() terra.StringValue {
	return terra.ReferenceAsString(t.ref.Append("create"))
}

func (t TimeoutsAttributes) Delete() terra.StringValue {
	return terra.ReferenceAsString(t.ref.Append("delete"))
}

func (t TimeoutsAttributes) Update() terra.StringValue {
	return terra.ReferenceAsString(t.ref.Append("update"))
}

type MountOptionsState struct {
	Export       string `json:"export"`
	ExportFull   string `json:"export_full"`
	Instructions string `json:"instructions"`
	Protocol     string `json:"protocol"`
}

type ExportPolicyState struct {
	Rules []ExportPolicyRulesState `json:"rules"`
}

type ExportPolicyRulesState struct {
	AccessType          string `json:"access_type"`
	AllowedClients      string `json:"allowed_clients"`
	HasRootAccess       string `json:"has_root_access"`
	Kerberos5ReadOnly   bool   `json:"kerberos5_read_only"`
	Kerberos5ReadWrite  bool   `json:"kerberos5_read_write"`
	Kerberos5IReadOnly  bool   `json:"kerberos5i_read_only"`
	Kerberos5IReadWrite bool   `json:"kerberos5i_read_write"`
	Kerberos5PReadOnly  bool   `json:"kerberos5p_read_only"`
	Kerberos5PReadWrite bool   `json:"kerberos5p_read_write"`
	Nfsv3               bool   `json:"nfsv3"`
	Nfsv4               bool   `json:"nfsv4"`
}

type RestoreParametersState struct {
	SourceBackup   string `json:"source_backup"`
	SourceSnapshot string `json:"source_snapshot"`
}

type SnapshotPolicyState struct {
	Enabled         bool                                 `json:"enabled"`
	DailySchedule   []SnapshotPolicyDailyScheduleState   `json:"daily_schedule"`
	HourlySchedule  []SnapshotPolicyHourlyScheduleState  `json:"hourly_schedule"`
	MonthlySchedule []SnapshotPolicyMonthlyScheduleState `json:"monthly_schedule"`
	WeeklySchedule  []SnapshotPolicyWeeklyScheduleState  `json:"weekly_schedule"`
}

type SnapshotPolicyDailyScheduleState struct {
	Hour            float64 `json:"hour"`
	Minute          float64 `json:"minute"`
	SnapshotsToKeep float64 `json:"snapshots_to_keep"`
}

type SnapshotPolicyHourlyScheduleState struct {
	Minute          float64 `json:"minute"`
	SnapshotsToKeep float64 `json:"snapshots_to_keep"`
}

type SnapshotPolicyMonthlyScheduleState struct {
	DaysOfMonth     string  `json:"days_of_month"`
	Hour            float64 `json:"hour"`
	Minute          float64 `json:"minute"`
	SnapshotsToKeep float64 `json:"snapshots_to_keep"`
}

type SnapshotPolicyWeeklyScheduleState struct {
	Day             string  `json:"day"`
	Hour            float64 `json:"hour"`
	Minute          float64 `json:"minute"`
	SnapshotsToKeep float64 `json:"snapshots_to_keep"`
}

type TimeoutsState struct {
	Create string `json:"create"`
	Delete string `json:"delete"`
	Update string `json:"update"`
}
