// CODE GENERATED BY github.com/volvo-cars/lingon. DO NOT EDIT.

package aws

import (
	"encoding/json"
	"fmt"
	"github.com/volvo-cars/lingon/pkg/terra"
	"io"
)

// NewAuditmanagerAssessmentDelegation creates a new instance of [AuditmanagerAssessmentDelegation].
func NewAuditmanagerAssessmentDelegation(name string, args AuditmanagerAssessmentDelegationArgs) *AuditmanagerAssessmentDelegation {
	return &AuditmanagerAssessmentDelegation{
		Args: args,
		Name: name,
	}
}

var _ terra.Resource = (*AuditmanagerAssessmentDelegation)(nil)

// AuditmanagerAssessmentDelegation represents the Terraform resource aws_auditmanager_assessment_delegation.
type AuditmanagerAssessmentDelegation struct {
	Name      string
	Args      AuditmanagerAssessmentDelegationArgs
	state     *auditmanagerAssessmentDelegationState
	DependsOn terra.Dependencies
	Lifecycle *terra.Lifecycle
}

// Type returns the Terraform object type for [AuditmanagerAssessmentDelegation].
func (aad *AuditmanagerAssessmentDelegation) Type() string {
	return "aws_auditmanager_assessment_delegation"
}

// LocalName returns the local name for [AuditmanagerAssessmentDelegation].
func (aad *AuditmanagerAssessmentDelegation) LocalName() string {
	return aad.Name
}

// Configuration returns the configuration (args) for [AuditmanagerAssessmentDelegation].
func (aad *AuditmanagerAssessmentDelegation) Configuration() interface{} {
	return aad.Args
}

// DependOn is used for other resources to depend on [AuditmanagerAssessmentDelegation].
func (aad *AuditmanagerAssessmentDelegation) DependOn() terra.Reference {
	return terra.ReferenceResource(aad)
}

// Dependencies returns the list of resources [AuditmanagerAssessmentDelegation] depends_on.
func (aad *AuditmanagerAssessmentDelegation) Dependencies() terra.Dependencies {
	return aad.DependsOn
}

// LifecycleManagement returns the lifecycle block for [AuditmanagerAssessmentDelegation].
func (aad *AuditmanagerAssessmentDelegation) LifecycleManagement() *terra.Lifecycle {
	return aad.Lifecycle
}

// Attributes returns the attributes for [AuditmanagerAssessmentDelegation].
func (aad *AuditmanagerAssessmentDelegation) Attributes() auditmanagerAssessmentDelegationAttributes {
	return auditmanagerAssessmentDelegationAttributes{ref: terra.ReferenceResource(aad)}
}

// ImportState imports the given attribute values into [AuditmanagerAssessmentDelegation]'s state.
func (aad *AuditmanagerAssessmentDelegation) ImportState(av io.Reader) error {
	aad.state = &auditmanagerAssessmentDelegationState{}
	if err := json.NewDecoder(av).Decode(aad.state); err != nil {
		return fmt.Errorf("decoding state into resource %s.%s: %w", aad.Type(), aad.LocalName(), err)
	}
	return nil
}

// State returns the state and a bool indicating if [AuditmanagerAssessmentDelegation] has state.
func (aad *AuditmanagerAssessmentDelegation) State() (*auditmanagerAssessmentDelegationState, bool) {
	return aad.state, aad.state != nil
}

// StateMust returns the state for [AuditmanagerAssessmentDelegation]. Panics if the state is nil.
func (aad *AuditmanagerAssessmentDelegation) StateMust() *auditmanagerAssessmentDelegationState {
	if aad.state == nil {
		panic(fmt.Sprintf("state is nil for resource %s.%s", aad.Type(), aad.LocalName()))
	}
	return aad.state
}

// AuditmanagerAssessmentDelegationArgs contains the configurations for aws_auditmanager_assessment_delegation.
type AuditmanagerAssessmentDelegationArgs struct {
	// AssessmentId: string, required
	AssessmentId terra.StringValue `hcl:"assessment_id,attr" validate:"required"`
	// Comment: string, optional
	Comment terra.StringValue `hcl:"comment,attr"`
	// ControlSetId: string, required
	ControlSetId terra.StringValue `hcl:"control_set_id,attr" validate:"required"`
	// RoleArn: string, required
	RoleArn terra.StringValue `hcl:"role_arn,attr" validate:"required"`
	// RoleType: string, required
	RoleType terra.StringValue `hcl:"role_type,attr" validate:"required"`
}
type auditmanagerAssessmentDelegationAttributes struct {
	ref terra.Reference
}

// AssessmentId returns a reference to field assessment_id of aws_auditmanager_assessment_delegation.
func (aad auditmanagerAssessmentDelegationAttributes) AssessmentId() terra.StringValue {
	return terra.ReferenceAsString(aad.ref.Append("assessment_id"))
}

// Comment returns a reference to field comment of aws_auditmanager_assessment_delegation.
func (aad auditmanagerAssessmentDelegationAttributes) Comment() terra.StringValue {
	return terra.ReferenceAsString(aad.ref.Append("comment"))
}

// ControlSetId returns a reference to field control_set_id of aws_auditmanager_assessment_delegation.
func (aad auditmanagerAssessmentDelegationAttributes) ControlSetId() terra.StringValue {
	return terra.ReferenceAsString(aad.ref.Append("control_set_id"))
}

// DelegationId returns a reference to field delegation_id of aws_auditmanager_assessment_delegation.
func (aad auditmanagerAssessmentDelegationAttributes) DelegationId() terra.StringValue {
	return terra.ReferenceAsString(aad.ref.Append("delegation_id"))
}

// Id returns a reference to field id of aws_auditmanager_assessment_delegation.
func (aad auditmanagerAssessmentDelegationAttributes) Id() terra.StringValue {
	return terra.ReferenceAsString(aad.ref.Append("id"))
}

// RoleArn returns a reference to field role_arn of aws_auditmanager_assessment_delegation.
func (aad auditmanagerAssessmentDelegationAttributes) RoleArn() terra.StringValue {
	return terra.ReferenceAsString(aad.ref.Append("role_arn"))
}

// RoleType returns a reference to field role_type of aws_auditmanager_assessment_delegation.
func (aad auditmanagerAssessmentDelegationAttributes) RoleType() terra.StringValue {
	return terra.ReferenceAsString(aad.ref.Append("role_type"))
}

// Status returns a reference to field status of aws_auditmanager_assessment_delegation.
func (aad auditmanagerAssessmentDelegationAttributes) Status() terra.StringValue {
	return terra.ReferenceAsString(aad.ref.Append("status"))
}

type auditmanagerAssessmentDelegationState struct {
	AssessmentId string `json:"assessment_id"`
	Comment      string `json:"comment"`
	ControlSetId string `json:"control_set_id"`
	DelegationId string `json:"delegation_id"`
	Id           string `json:"id"`
	RoleArn      string `json:"role_arn"`
	RoleType     string `json:"role_type"`
	Status       string `json:"status"`
}
