// CODE GENERATED BY github.com/volvo-cars/lingon. DO NOT EDIT.

package aws

import (
	"encoding/json"
	"fmt"
	"github.com/volvo-cars/lingon/pkg/terra"
	"io"
)

func NewChimeVoiceConnector(name string, args ChimeVoiceConnectorArgs) *ChimeVoiceConnector {
	return &ChimeVoiceConnector{
		Args: args,
		Name: name,
	}
}

var _ terra.Resource = (*ChimeVoiceConnector)(nil)

type ChimeVoiceConnector struct {
	Name  string
	Args  ChimeVoiceConnectorArgs
	state *chimeVoiceConnectorState
}

func (cvc *ChimeVoiceConnector) Type() string {
	return "aws_chime_voice_connector"
}

func (cvc *ChimeVoiceConnector) LocalName() string {
	return cvc.Name
}

func (cvc *ChimeVoiceConnector) Configuration() interface{} {
	return cvc.Args
}

func (cvc *ChimeVoiceConnector) Attributes() chimeVoiceConnectorAttributes {
	return chimeVoiceConnectorAttributes{ref: terra.ReferenceResource(cvc)}
}

func (cvc *ChimeVoiceConnector) ImportState(av io.Reader) error {
	cvc.state = &chimeVoiceConnectorState{}
	if err := json.NewDecoder(av).Decode(cvc.state); err != nil {
		return fmt.Errorf("decoding state into resource %s.%s: %w", cvc.Type(), cvc.LocalName(), err)
	}
	return nil
}

func (cvc *ChimeVoiceConnector) State() (*chimeVoiceConnectorState, bool) {
	return cvc.state, cvc.state != nil
}

func (cvc *ChimeVoiceConnector) StateMust() *chimeVoiceConnectorState {
	if cvc.state == nil {
		panic(fmt.Sprintf("state is nil for resource %s.%s", cvc.Type(), cvc.LocalName()))
	}
	return cvc.state
}

func (cvc *ChimeVoiceConnector) DependOn() terra.Reference {
	return terra.ReferenceResource(cvc)
}

type ChimeVoiceConnectorArgs struct {
	// AwsRegion: string, optional
	AwsRegion terra.StringValue `hcl:"aws_region,attr"`
	// Id: string, optional
	Id terra.StringValue `hcl:"id,attr"`
	// Name: string, required
	Name terra.StringValue `hcl:"name,attr" validate:"required"`
	// RequireEncryption: bool, required
	RequireEncryption terra.BoolValue `hcl:"require_encryption,attr" validate:"required"`
	// DependsOn contains resources that ChimeVoiceConnector depends on
	DependsOn terra.Dependencies `hcl:"depends_on,attr"`
}
type chimeVoiceConnectorAttributes struct {
	ref terra.Reference
}

func (cvc chimeVoiceConnectorAttributes) AwsRegion() terra.StringValue {
	return terra.ReferenceString(cvc.ref.Append("aws_region"))
}

func (cvc chimeVoiceConnectorAttributes) Id() terra.StringValue {
	return terra.ReferenceString(cvc.ref.Append("id"))
}

func (cvc chimeVoiceConnectorAttributes) Name() terra.StringValue {
	return terra.ReferenceString(cvc.ref.Append("name"))
}

func (cvc chimeVoiceConnectorAttributes) OutboundHostName() terra.StringValue {
	return terra.ReferenceString(cvc.ref.Append("outbound_host_name"))
}

func (cvc chimeVoiceConnectorAttributes) RequireEncryption() terra.BoolValue {
	return terra.ReferenceBool(cvc.ref.Append("require_encryption"))
}

type chimeVoiceConnectorState struct {
	AwsRegion         string `json:"aws_region"`
	Id                string `json:"id"`
	Name              string `json:"name"`
	OutboundHostName  string `json:"outbound_host_name"`
	RequireEncryption bool   `json:"require_encryption"`
}
