// CODE GENERATED BY github.com/volvo-cars/lingon. DO NOT EDIT.

package aws

import (
	dataservicediscoveryservice "github.com/golingon/terraproviders/aws/4.60.0/dataservicediscoveryservice"
	"github.com/volvo-cars/lingon/pkg/terra"
)

func NewDataServiceDiscoveryService(name string, args DataServiceDiscoveryServiceArgs) *DataServiceDiscoveryService {
	return &DataServiceDiscoveryService{
		Args: args,
		Name: name,
	}
}

var _ terra.DataResource = (*DataServiceDiscoveryService)(nil)

type DataServiceDiscoveryService struct {
	Name string
	Args DataServiceDiscoveryServiceArgs
}

func (sds *DataServiceDiscoveryService) DataSource() string {
	return "aws_service_discovery_service"
}

func (sds *DataServiceDiscoveryService) LocalName() string {
	return sds.Name
}

func (sds *DataServiceDiscoveryService) Configuration() interface{} {
	return sds.Args
}

func (sds *DataServiceDiscoveryService) Attributes() dataServiceDiscoveryServiceAttributes {
	return dataServiceDiscoveryServiceAttributes{ref: terra.ReferenceDataResource(sds)}
}

type DataServiceDiscoveryServiceArgs struct {
	// Id: string, optional
	Id terra.StringValue `hcl:"id,attr"`
	// Name: string, required
	Name terra.StringValue `hcl:"name,attr" validate:"required"`
	// NamespaceId: string, required
	NamespaceId terra.StringValue `hcl:"namespace_id,attr" validate:"required"`
	// Tags: map of string, optional
	Tags terra.MapValue[terra.StringValue] `hcl:"tags,attr"`
	// TagsAll: map of string, optional
	TagsAll terra.MapValue[terra.StringValue] `hcl:"tags_all,attr"`
	// DnsConfig: min=0
	DnsConfig []dataservicediscoveryservice.DnsConfig `hcl:"dns_config,block" validate:"min=0"`
	// HealthCheckConfig: min=0
	HealthCheckConfig []dataservicediscoveryservice.HealthCheckConfig `hcl:"health_check_config,block" validate:"min=0"`
	// HealthCheckCustomConfig: min=0
	HealthCheckCustomConfig []dataservicediscoveryservice.HealthCheckCustomConfig `hcl:"health_check_custom_config,block" validate:"min=0"`
}
type dataServiceDiscoveryServiceAttributes struct {
	ref terra.Reference
}

func (sds dataServiceDiscoveryServiceAttributes) Arn() terra.StringValue {
	return terra.ReferenceString(sds.ref.Append("arn"))
}

func (sds dataServiceDiscoveryServiceAttributes) Description() terra.StringValue {
	return terra.ReferenceString(sds.ref.Append("description"))
}

func (sds dataServiceDiscoveryServiceAttributes) Id() terra.StringValue {
	return terra.ReferenceString(sds.ref.Append("id"))
}

func (sds dataServiceDiscoveryServiceAttributes) Name() terra.StringValue {
	return terra.ReferenceString(sds.ref.Append("name"))
}

func (sds dataServiceDiscoveryServiceAttributes) NamespaceId() terra.StringValue {
	return terra.ReferenceString(sds.ref.Append("namespace_id"))
}

func (sds dataServiceDiscoveryServiceAttributes) Tags() terra.MapValue[terra.StringValue] {
	return terra.ReferenceMap[terra.StringValue](sds.ref.Append("tags"))
}

func (sds dataServiceDiscoveryServiceAttributes) TagsAll() terra.MapValue[terra.StringValue] {
	return terra.ReferenceMap[terra.StringValue](sds.ref.Append("tags_all"))
}

func (sds dataServiceDiscoveryServiceAttributes) DnsConfig() terra.ListValue[dataservicediscoveryservice.DnsConfigAttributes] {
	return terra.ReferenceList[dataservicediscoveryservice.DnsConfigAttributes](sds.ref.Append("dns_config"))
}

func (sds dataServiceDiscoveryServiceAttributes) HealthCheckConfig() terra.ListValue[dataservicediscoveryservice.HealthCheckConfigAttributes] {
	return terra.ReferenceList[dataservicediscoveryservice.HealthCheckConfigAttributes](sds.ref.Append("health_check_config"))
}

func (sds dataServiceDiscoveryServiceAttributes) HealthCheckCustomConfig() terra.ListValue[dataservicediscoveryservice.HealthCheckCustomConfigAttributes] {
	return terra.ReferenceList[dataservicediscoveryservice.HealthCheckCustomConfigAttributes](sds.ref.Append("health_check_custom_config"))
}
