// CODE GENERATED BY github.com/volvo-cars/lingon. DO NOT EDIT.

package aws

import (
	"encoding/json"
	"fmt"
	s3bucketanalyticsconfiguration "github.com/golingon/terraproviders/aws/4.60.0/s3bucketanalyticsconfiguration"
	"github.com/volvo-cars/lingon/pkg/terra"
	"io"
)

func NewS3BucketAnalyticsConfiguration(name string, args S3BucketAnalyticsConfigurationArgs) *S3BucketAnalyticsConfiguration {
	return &S3BucketAnalyticsConfiguration{
		Args: args,
		Name: name,
	}
}

var _ terra.Resource = (*S3BucketAnalyticsConfiguration)(nil)

type S3BucketAnalyticsConfiguration struct {
	Name  string
	Args  S3BucketAnalyticsConfigurationArgs
	state *s3BucketAnalyticsConfigurationState
}

func (sbac *S3BucketAnalyticsConfiguration) Type() string {
	return "aws_s3_bucket_analytics_configuration"
}

func (sbac *S3BucketAnalyticsConfiguration) LocalName() string {
	return sbac.Name
}

func (sbac *S3BucketAnalyticsConfiguration) Configuration() interface{} {
	return sbac.Args
}

func (sbac *S3BucketAnalyticsConfiguration) Attributes() s3BucketAnalyticsConfigurationAttributes {
	return s3BucketAnalyticsConfigurationAttributes{ref: terra.ReferenceResource(sbac)}
}

func (sbac *S3BucketAnalyticsConfiguration) ImportState(av io.Reader) error {
	sbac.state = &s3BucketAnalyticsConfigurationState{}
	if err := json.NewDecoder(av).Decode(sbac.state); err != nil {
		return fmt.Errorf("decoding state into resource %s.%s: %w", sbac.Type(), sbac.LocalName(), err)
	}
	return nil
}

func (sbac *S3BucketAnalyticsConfiguration) State() (*s3BucketAnalyticsConfigurationState, bool) {
	return sbac.state, sbac.state != nil
}

func (sbac *S3BucketAnalyticsConfiguration) StateMust() *s3BucketAnalyticsConfigurationState {
	if sbac.state == nil {
		panic(fmt.Sprintf("state is nil for resource %s.%s", sbac.Type(), sbac.LocalName()))
	}
	return sbac.state
}

func (sbac *S3BucketAnalyticsConfiguration) DependOn() terra.Reference {
	return terra.ReferenceResource(sbac)
}

type S3BucketAnalyticsConfigurationArgs struct {
	// Bucket: string, required
	Bucket terra.StringValue `hcl:"bucket,attr" validate:"required"`
	// Id: string, optional
	Id terra.StringValue `hcl:"id,attr"`
	// Name: string, required
	Name terra.StringValue `hcl:"name,attr" validate:"required"`
	// Filter: optional
	Filter *s3bucketanalyticsconfiguration.Filter `hcl:"filter,block"`
	// StorageClassAnalysis: optional
	StorageClassAnalysis *s3bucketanalyticsconfiguration.StorageClassAnalysis `hcl:"storage_class_analysis,block"`
	// DependsOn contains resources that S3BucketAnalyticsConfiguration depends on
	DependsOn terra.Dependencies `hcl:"depends_on,attr"`
}
type s3BucketAnalyticsConfigurationAttributes struct {
	ref terra.Reference
}

func (sbac s3BucketAnalyticsConfigurationAttributes) Bucket() terra.StringValue {
	return terra.ReferenceString(sbac.ref.Append("bucket"))
}

func (sbac s3BucketAnalyticsConfigurationAttributes) Id() terra.StringValue {
	return terra.ReferenceString(sbac.ref.Append("id"))
}

func (sbac s3BucketAnalyticsConfigurationAttributes) Name() terra.StringValue {
	return terra.ReferenceString(sbac.ref.Append("name"))
}

func (sbac s3BucketAnalyticsConfigurationAttributes) Filter() terra.ListValue[s3bucketanalyticsconfiguration.FilterAttributes] {
	return terra.ReferenceList[s3bucketanalyticsconfiguration.FilterAttributes](sbac.ref.Append("filter"))
}

func (sbac s3BucketAnalyticsConfigurationAttributes) StorageClassAnalysis() terra.ListValue[s3bucketanalyticsconfiguration.StorageClassAnalysisAttributes] {
	return terra.ReferenceList[s3bucketanalyticsconfiguration.StorageClassAnalysisAttributes](sbac.ref.Append("storage_class_analysis"))
}

type s3BucketAnalyticsConfigurationState struct {
	Bucket               string                                                     `json:"bucket"`
	Id                   string                                                     `json:"id"`
	Name                 string                                                     `json:"name"`
	Filter               []s3bucketanalyticsconfiguration.FilterState               `json:"filter"`
	StorageClassAnalysis []s3bucketanalyticsconfiguration.StorageClassAnalysisState `json:"storage_class_analysis"`
}
