// CODE GENERATED BY github.com/golingon/lingon. DO NOT EDIT.

package aws_kms_external_key

import (
	"encoding/json"
	"fmt"
	"github.com/golingon/lingon/pkg/terra"
	"io"
)

// New creates a new instance of [Resource].
func New(name string, args Args) *Resource {
	return &Resource{
		Args: args,
		Name: name,
	}
}

var _ terra.Resource = (*Resource)(nil)

// Resource represents the Terraform resource aws_kms_external_key.
type Resource struct {
	Name      string
	Args      Args
	state     *awsKmsExternalKeyState
	DependsOn terra.Dependencies
	Lifecycle *terra.Lifecycle
}

// Type returns the Terraform object type for [Resource].
func (akek *Resource) Type() string {
	return "aws_kms_external_key"
}

// LocalName returns the local name for [Resource].
func (akek *Resource) LocalName() string {
	return akek.Name
}

// Configuration returns the configuration (args) for [Resource].
func (akek *Resource) Configuration() interface{} {
	return akek.Args
}

// DependOn is used for other resources to depend on [Resource].
func (akek *Resource) DependOn() terra.Reference {
	return terra.ReferenceResource(akek)
}

// Dependencies returns the list of resources [Resource] depends_on.
func (akek *Resource) Dependencies() terra.Dependencies {
	return akek.DependsOn
}

// LifecycleManagement returns the lifecycle block for [Resource].
func (akek *Resource) LifecycleManagement() *terra.Lifecycle {
	return akek.Lifecycle
}

// Attributes returns the attributes for [Resource].
func (akek *Resource) Attributes() awsKmsExternalKeyAttributes {
	return awsKmsExternalKeyAttributes{ref: terra.ReferenceResource(akek)}
}

// ImportState imports the given attribute values into [Resource]'s state.
func (akek *Resource) ImportState(state io.Reader) error {
	akek.state = &awsKmsExternalKeyState{}
	if err := json.NewDecoder(state).Decode(akek.state); err != nil {
		return fmt.Errorf("decoding state into resource %s.%s: %w", akek.Type(), akek.LocalName(), err)
	}
	return nil
}

// State returns the state and a bool indicating if [Resource] has state.
func (akek *Resource) State() (*awsKmsExternalKeyState, bool) {
	return akek.state, akek.state != nil
}

// StateMust returns the state for [Resource]. Panics if the state is nil.
func (akek *Resource) StateMust() *awsKmsExternalKeyState {
	if akek.state == nil {
		panic(fmt.Sprintf("state is nil for resource %s.%s", akek.Type(), akek.LocalName()))
	}
	return akek.state
}

// Args contains the configurations for aws_kms_external_key.
type Args struct {
	// BypassPolicyLockoutSafetyCheck: bool, optional
	BypassPolicyLockoutSafetyCheck terra.BoolValue `hcl:"bypass_policy_lockout_safety_check,attr"`
	// DeletionWindowInDays: number, optional
	DeletionWindowInDays terra.NumberValue `hcl:"deletion_window_in_days,attr"`
	// Description: string, optional
	Description terra.StringValue `hcl:"description,attr"`
	// Enabled: bool, optional
	Enabled terra.BoolValue `hcl:"enabled,attr"`
	// Id: string, optional
	Id terra.StringValue `hcl:"id,attr"`
	// KeyMaterialBase64: string, optional
	KeyMaterialBase64 terra.StringValue `hcl:"key_material_base64,attr"`
	// MultiRegion: bool, optional
	MultiRegion terra.BoolValue `hcl:"multi_region,attr"`
	// Policy: string, optional
	Policy terra.StringValue `hcl:"policy,attr"`
	// Tags: map of string, optional
	Tags terra.MapValue[terra.StringValue] `hcl:"tags,attr"`
	// TagsAll: map of string, optional
	TagsAll terra.MapValue[terra.StringValue] `hcl:"tags_all,attr"`
	// ValidTo: string, optional
	ValidTo terra.StringValue `hcl:"valid_to,attr"`
}

type awsKmsExternalKeyAttributes struct {
	ref terra.Reference
}

// Arn returns a reference to field arn of aws_kms_external_key.
func (akek awsKmsExternalKeyAttributes) Arn() terra.StringValue {
	return terra.ReferenceAsString(akek.ref.Append("arn"))
}

// BypassPolicyLockoutSafetyCheck returns a reference to field bypass_policy_lockout_safety_check of aws_kms_external_key.
func (akek awsKmsExternalKeyAttributes) BypassPolicyLockoutSafetyCheck() terra.BoolValue {
	return terra.ReferenceAsBool(akek.ref.Append("bypass_policy_lockout_safety_check"))
}

// DeletionWindowInDays returns a reference to field deletion_window_in_days of aws_kms_external_key.
func (akek awsKmsExternalKeyAttributes) DeletionWindowInDays() terra.NumberValue {
	return terra.ReferenceAsNumber(akek.ref.Append("deletion_window_in_days"))
}

// Description returns a reference to field description of aws_kms_external_key.
func (akek awsKmsExternalKeyAttributes) Description() terra.StringValue {
	return terra.ReferenceAsString(akek.ref.Append("description"))
}

// Enabled returns a reference to field enabled of aws_kms_external_key.
func (akek awsKmsExternalKeyAttributes) Enabled() terra.BoolValue {
	return terra.ReferenceAsBool(akek.ref.Append("enabled"))
}

// ExpirationModel returns a reference to field expiration_model of aws_kms_external_key.
func (akek awsKmsExternalKeyAttributes) ExpirationModel() terra.StringValue {
	return terra.ReferenceAsString(akek.ref.Append("expiration_model"))
}

// Id returns a reference to field id of aws_kms_external_key.
func (akek awsKmsExternalKeyAttributes) Id() terra.StringValue {
	return terra.ReferenceAsString(akek.ref.Append("id"))
}

// KeyMaterialBase64 returns a reference to field key_material_base64 of aws_kms_external_key.
func (akek awsKmsExternalKeyAttributes) KeyMaterialBase64() terra.StringValue {
	return terra.ReferenceAsString(akek.ref.Append("key_material_base64"))
}

// KeyState returns a reference to field key_state of aws_kms_external_key.
func (akek awsKmsExternalKeyAttributes) KeyState() terra.StringValue {
	return terra.ReferenceAsString(akek.ref.Append("key_state"))
}

// KeyUsage returns a reference to field key_usage of aws_kms_external_key.
func (akek awsKmsExternalKeyAttributes) KeyUsage() terra.StringValue {
	return terra.ReferenceAsString(akek.ref.Append("key_usage"))
}

// MultiRegion returns a reference to field multi_region of aws_kms_external_key.
func (akek awsKmsExternalKeyAttributes) MultiRegion() terra.BoolValue {
	return terra.ReferenceAsBool(akek.ref.Append("multi_region"))
}

// Policy returns a reference to field policy of aws_kms_external_key.
func (akek awsKmsExternalKeyAttributes) Policy() terra.StringValue {
	return terra.ReferenceAsString(akek.ref.Append("policy"))
}

// Tags returns a reference to field tags of aws_kms_external_key.
func (akek awsKmsExternalKeyAttributes) Tags() terra.MapValue[terra.StringValue] {
	return terra.ReferenceAsMap[terra.StringValue](akek.ref.Append("tags"))
}

// TagsAll returns a reference to field tags_all of aws_kms_external_key.
func (akek awsKmsExternalKeyAttributes) TagsAll() terra.MapValue[terra.StringValue] {
	return terra.ReferenceAsMap[terra.StringValue](akek.ref.Append("tags_all"))
}

// ValidTo returns a reference to field valid_to of aws_kms_external_key.
func (akek awsKmsExternalKeyAttributes) ValidTo() terra.StringValue {
	return terra.ReferenceAsString(akek.ref.Append("valid_to"))
}

type awsKmsExternalKeyState struct {
	Arn                            string            `json:"arn"`
	BypassPolicyLockoutSafetyCheck bool              `json:"bypass_policy_lockout_safety_check"`
	DeletionWindowInDays           float64           `json:"deletion_window_in_days"`
	Description                    string            `json:"description"`
	Enabled                        bool              `json:"enabled"`
	ExpirationModel                string            `json:"expiration_model"`
	Id                             string            `json:"id"`
	KeyMaterialBase64              string            `json:"key_material_base64"`
	KeyState                       string            `json:"key_state"`
	KeyUsage                       string            `json:"key_usage"`
	MultiRegion                    bool              `json:"multi_region"`
	Policy                         string            `json:"policy"`
	Tags                           map[string]string `json:"tags"`
	TagsAll                        map[string]string `json:"tags_all"`
	ValidTo                        string            `json:"valid_to"`
}
