// CODE GENERATED BY github.com/golingon/lingon. DO NOT EDIT.

package google_secret_manager_secret_iam_policy

import "github.com/golingon/lingon/pkg/terra"

// Data creates a new instance of [DataSource].
func Data(name string, args DataArgs) *DataSource {
	return &DataSource{
		Args: args,
		Name: name,
	}
}

var _ terra.DataSource = (*DataSource)(nil)

// DataSource represents the Terraform data resource google_secret_manager_secret_iam_policy.
type DataSource struct {
	Name string
	Args DataArgs
}

// DataSource returns the Terraform object type for [DataSource].
func (gsmsip *DataSource) DataSource() string {
	return "google_secret_manager_secret_iam_policy"
}

// LocalName returns the local name for [DataSource].
func (gsmsip *DataSource) LocalName() string {
	return gsmsip.Name
}

// Configuration returns the configuration (args) for [DataSource].
func (gsmsip *DataSource) Configuration() interface{} {
	return gsmsip.Args
}

// Attributes returns the attributes for [DataSource].
func (gsmsip *DataSource) Attributes() dataGoogleSecretManagerSecretIamPolicyAttributes {
	return dataGoogleSecretManagerSecretIamPolicyAttributes{ref: terra.ReferenceDataSource(gsmsip)}
}

// DataArgs contains the configurations for google_secret_manager_secret_iam_policy.
type DataArgs struct {
	// Id: string, optional
	Id terra.StringValue `hcl:"id,attr"`
	// Project: string, optional
	Project terra.StringValue `hcl:"project,attr"`
	// SecretId: string, required
	SecretId terra.StringValue `hcl:"secret_id,attr" validate:"required"`
}

type dataGoogleSecretManagerSecretIamPolicyAttributes struct {
	ref terra.Reference
}

// Etag returns a reference to field etag of google_secret_manager_secret_iam_policy.
func (gsmsip dataGoogleSecretManagerSecretIamPolicyAttributes) Etag() terra.StringValue {
	return terra.ReferenceAsString(gsmsip.ref.Append("etag"))
}

// Id returns a reference to field id of google_secret_manager_secret_iam_policy.
func (gsmsip dataGoogleSecretManagerSecretIamPolicyAttributes) Id() terra.StringValue {
	return terra.ReferenceAsString(gsmsip.ref.Append("id"))
}

// PolicyData returns a reference to field policy_data of google_secret_manager_secret_iam_policy.
func (gsmsip dataGoogleSecretManagerSecretIamPolicyAttributes) PolicyData() terra.StringValue {
	return terra.ReferenceAsString(gsmsip.ref.Append("policy_data"))
}

// Project returns a reference to field project of google_secret_manager_secret_iam_policy.
func (gsmsip dataGoogleSecretManagerSecretIamPolicyAttributes) Project() terra.StringValue {
	return terra.ReferenceAsString(gsmsip.ref.Append("project"))
}

// SecretId returns a reference to field secret_id of google_secret_manager_secret_iam_policy.
func (gsmsip dataGoogleSecretManagerSecretIamPolicyAttributes) SecretId() terra.StringValue {
	return terra.ReferenceAsString(gsmsip.ref.Append("secret_id"))
}
