// CODE GENERATED BY github.com/golingon/lingon. DO NOT EDIT.

package aws_efs_mount_target

import "github.com/golingon/lingon/pkg/terra"

// Data creates a new instance of [DataSource].
func Data(name string, args DataArgs) *DataSource {
	return &DataSource{
		Args: args,
		Name: name,
	}
}

var _ terra.DataSource = (*DataSource)(nil)

// DataSource represents the Terraform data resource aws_efs_mount_target.
type DataSource struct {
	Name string
	Args DataArgs
}

// DataSource returns the Terraform object type for [DataSource].
func (aemt *DataSource) DataSource() string {
	return "aws_efs_mount_target"
}

// LocalName returns the local name for [DataSource].
func (aemt *DataSource) LocalName() string {
	return aemt.Name
}

// Configuration returns the configuration (args) for [DataSource].
func (aemt *DataSource) Configuration() interface{} {
	return aemt.Args
}

// Attributes returns the attributes for [DataSource].
func (aemt *DataSource) Attributes() dataAwsEfsMountTargetAttributes {
	return dataAwsEfsMountTargetAttributes{ref: terra.ReferenceDataSource(aemt)}
}

// DataArgs contains the configurations for aws_efs_mount_target.
type DataArgs struct {
	// AccessPointId: string, optional
	AccessPointId terra.StringValue `hcl:"access_point_id,attr"`
	// FileSystemId: string, optional
	FileSystemId terra.StringValue `hcl:"file_system_id,attr"`
	// Id: string, optional
	Id terra.StringValue `hcl:"id,attr"`
	// MountTargetId: string, optional
	MountTargetId terra.StringValue `hcl:"mount_target_id,attr"`
}

type dataAwsEfsMountTargetAttributes struct {
	ref terra.Reference
}

// AccessPointId returns a reference to field access_point_id of aws_efs_mount_target.
func (aemt dataAwsEfsMountTargetAttributes) AccessPointId() terra.StringValue {
	return terra.ReferenceAsString(aemt.ref.Append("access_point_id"))
}

// AvailabilityZoneId returns a reference to field availability_zone_id of aws_efs_mount_target.
func (aemt dataAwsEfsMountTargetAttributes) AvailabilityZoneId() terra.StringValue {
	return terra.ReferenceAsString(aemt.ref.Append("availability_zone_id"))
}

// AvailabilityZoneName returns a reference to field availability_zone_name of aws_efs_mount_target.
func (aemt dataAwsEfsMountTargetAttributes) AvailabilityZoneName() terra.StringValue {
	return terra.ReferenceAsString(aemt.ref.Append("availability_zone_name"))
}

// DnsName returns a reference to field dns_name of aws_efs_mount_target.
func (aemt dataAwsEfsMountTargetAttributes) DnsName() terra.StringValue {
	return terra.ReferenceAsString(aemt.ref.Append("dns_name"))
}

// FileSystemArn returns a reference to field file_system_arn of aws_efs_mount_target.
func (aemt dataAwsEfsMountTargetAttributes) FileSystemArn() terra.StringValue {
	return terra.ReferenceAsString(aemt.ref.Append("file_system_arn"))
}

// FileSystemId returns a reference to field file_system_id of aws_efs_mount_target.
func (aemt dataAwsEfsMountTargetAttributes) FileSystemId() terra.StringValue {
	return terra.ReferenceAsString(aemt.ref.Append("file_system_id"))
}

// Id returns a reference to field id of aws_efs_mount_target.
func (aemt dataAwsEfsMountTargetAttributes) Id() terra.StringValue {
	return terra.ReferenceAsString(aemt.ref.Append("id"))
}

// IpAddress returns a reference to field ip_address of aws_efs_mount_target.
func (aemt dataAwsEfsMountTargetAttributes) IpAddress() terra.StringValue {
	return terra.ReferenceAsString(aemt.ref.Append("ip_address"))
}

// MountTargetDnsName returns a reference to field mount_target_dns_name of aws_efs_mount_target.
func (aemt dataAwsEfsMountTargetAttributes) MountTargetDnsName() terra.StringValue {
	return terra.ReferenceAsString(aemt.ref.Append("mount_target_dns_name"))
}

// MountTargetId returns a reference to field mount_target_id of aws_efs_mount_target.
func (aemt dataAwsEfsMountTargetAttributes) MountTargetId() terra.StringValue {
	return terra.ReferenceAsString(aemt.ref.Append("mount_target_id"))
}

// NetworkInterfaceId returns a reference to field network_interface_id of aws_efs_mount_target.
func (aemt dataAwsEfsMountTargetAttributes) NetworkInterfaceId() terra.StringValue {
	return terra.ReferenceAsString(aemt.ref.Append("network_interface_id"))
}

// OwnerId returns a reference to field owner_id of aws_efs_mount_target.
func (aemt dataAwsEfsMountTargetAttributes) OwnerId() terra.StringValue {
	return terra.ReferenceAsString(aemt.ref.Append("owner_id"))
}

// SecurityGroups returns a reference to field security_groups of aws_efs_mount_target.
func (aemt dataAwsEfsMountTargetAttributes) SecurityGroups() terra.SetValue[terra.StringValue] {
	return terra.ReferenceAsSet[terra.StringValue](aemt.ref.Append("security_groups"))
}

// SubnetId returns a reference to field subnet_id of aws_efs_mount_target.
func (aemt dataAwsEfsMountTargetAttributes) SubnetId() terra.StringValue {
	return terra.ReferenceAsString(aemt.ref.Append("subnet_id"))
}
