
name: Update providers

on: 
  #push
  schedule:
    - cron: '0 6 * * 1' # at 6 on Mondays # https://crontab.guru/#0_6_*_*_1

permissions:
  contents: write

jobs:
  report:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@f43a0e5ff2bd294095638e18286ca9a3d1956744 # v3.6.0
        with:
          fetch-depth: 1

      - uses: actions/setup-go@93397bea11091df50f3d7e59dc26a7711a8bcfbe # v4.1.0
        with:
          go-version-file: './go.mod'
          check-latest: true
          cache-dependency-path: ./go.mod

      - name: Commit updated providers
        run: |
          # only commits if there are changes to commit
          ./ci.sh
