
name: Update providers

on: 
  push
  #  schedule:
  #    - cron: '0 6 * * 1' # at 6 on Mondays # https://crontab.guru/#0_6_*_*_1
  #      #- cron: '*/15 * * * *' # For testing

permissions:
  contents: write

jobs:
  report:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@ac593985615ec2ede58e132d2e21d2b1cbd6127c # v3.3.0
        with:
          fetch-depth: 1

      - uses: actions/setup-go@fac708d6674e30b6ba41289acaab6d4b75aa0753 # v4.0.1
        with:
          check-latest: true
          cache-dependency-path: ./go.mod

      - name: Commit updated providers
        run: |
          go generate .

          # only commits if there are changes to commit
          [ ! -z "$(git status --porcelain)" ]  && \
            git config --global user.name 'lingonbot' && \
            git config --global user.email 'lingonbot@users.noreply.github.com' && \
            git commit -am "automated update of providers" && \
            git push
